export type Point = { lat: number; lng: number }

export type MapConfidence = 'attested' | 'traditional' | 'mythic'
export type MythCategory = 'gods' | 'heroes' | 'odyssey' | 'trojan'

export type MythScene = {
  id: string
  title: string
  eyebrow: string
  cycle: string
  category: MythCategory
  location: string
  coordinates: Point
  accuracyRadiusKm: number
  mapConfidence: MapConfidence
  geographyNote: string
  pleiadesUrl?: string
  image: string
  fallback: string
  prompt: string
  clues: string[]
  options: string[]
  reveal: string
  source: string
  sourceNote: string
  symbol: string
}

export const mythScenes: MythScene[] = [
  {
    id: 'labyrinth',
    title: 'Theseus and the Minotaur',
    eyebrow: 'Cretan Cycle',
    cycle: 'Age of Heroes',
    category: 'heroes',
    location: 'Knossos, Crete',
    coordinates: { lat: 35.2989, lng: 25.1603 },
    accuracyRadiusKm: 30,
    mapConfidence: 'attested',
    geographyNote: 'The myth is associated with Knossos; the archaeological palace is not literally the maze of the story.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/589872',
    image: './assets/scene-labyrinth.webp',
    fallback: 'linear-gradient(118deg, #13110d 0%, #4e2b1e 44%, #a56136 100%)',
    prompt: 'Find the double axes on the walls, the distant horned shadow, and the red thread crossing the floor.',
    clues: [
      'The thread was left so that its bearer could find the way out again.',
      'This palace belongs to the island ruled by King Minos.',
      'The creature is half man and half bull.',
    ],
    options: ['Orpheus and Eurydice', 'Theseus and the Minotaur', 'Heracles and the Hydra', 'Bellerophon and the Chimera'],
    reveal:
      'With Ariadne’s thread, Theseus escapes the labyrinth designed by Daedalus. The myth is tied to Knossos, although the excavated palace and the legendary maze are not the same thing.',
    source: 'Apollodorus — Bibliotheca; Plutarch — Theseus',
    sourceNote: 'Ancient versions disagree on several details.',
    symbol: '𐂂',
  },
  {
    id: 'medusa',
    title: 'Perseus and Medusa',
    eyebrow: 'Perseus Cycle',
    cycle: 'Age of Heroes',
    category: 'heroes',
    location: 'The far western edge of Oceanus',
    coordinates: { lat: 35.9, lng: -7.2 },
    accuracyRadiusKm: 140,
    mapConfidence: 'mythic',
    geographyNote: 'Ancient poetry places the Gorgons in the distant west; this pin visualises a mythic direction, not an excavated site.',
    image: './assets/scene-medusa.webp',
    fallback: 'linear-gradient(120deg, #101713 0%, #31453d 45%, #a09878 100%)',
    prompt: 'Do not look directly. Petrified warriors and a mirror-bright shield should be enough.',
    clues: [
      'The hero watches his target only through a reflection in his shield.',
      'Athena gave him a polished shield; Hermes supplied a curved blade.',
      'The monster’s hair is made of living snakes.',
    ],
    options: ['Apollo and Python', 'Cadmus and the Dragon', 'Perseus and Medusa', 'Odysseus and Polyphemus'],
    reveal:
      'Perseus uses the polished shield as a mirror to avoid Medusa’s gaze. Ancient authors place the Gorgons near the remote western boundary of the imagined world.',
    source: 'Hesiod — Theogony; Apollodorus — Bibliotheca II',
    sourceNote: 'The map pin is an explicitly mythic placement, not a claim of historical precision.',
    symbol: '◉',
  },
  {
    id: 'sirens',
    title: 'Odysseus and the Sirens',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'The Siren Rocks, traditional Campanian placement',
    coordinates: { lat: 40.5808, lng: 14.4296 },
    accuracyRadiusKm: 45,
    mapConfidence: 'traditional',
    geographyNote: 'Homer gives no secure coordinates; later tradition often identifies the Sirens with islands off Campania.',
    image: './assets/scene-sirens.webp',
    fallback: 'linear-gradient(132deg, #071c24 0%, #22616a 48%, #e0a45e 100%)',
    prompt: 'Study the storm-dark water, the wax-sealed ears, and the traveller bound to the mast.',
    clues: [
      'The crew’s ears have been sealed with beeswax.',
      'The captain wants to hear the song, so he has himself tied to the mast.',
      'This happens during the voyage home from Troy to Ithaca.',
    ],
    options: ['Jason and the Harpies', 'Theseus and Ariadne', 'The Fall of Phaethon', 'Odysseus and the Sirens'],
    reveal:
      'Following Circe’s warning, Odysseus seals his crew’s ears with wax and has himself bound to the mast. He hears the Sirens and survives.',
    source: 'Homer — Odyssey XII',
    sourceNote: 'The exact location of the Sirens changes across ancient and modern interpretations.',
    symbol: '≈',
  },
  {
    id: 'trojan-horse',
    title: 'The Trojan Horse',
    eyebrow: 'Trojan Cycle',
    cycle: 'Trojan War',
    category: 'trojan',
    location: 'Ilion / Troy, Anatolia',
    coordinates: { lat: 39.9575, lng: 26.2389 },
    accuracyRadiusKm: 25,
    mapConfidence: 'attested',
    geographyNote: 'The pin marks the archaeological mound at Hisarlık, identified with ancient Ilion/Troy.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/550595',
    image: './assets/scene-trojan-horse.webp',
    fallback: 'linear-gradient(126deg, #17130f 0%, #744425 49%, #df9b4d 100%)',
    prompt: 'Look for the open gates at dawn, the abandoned shore, and the immense wooden offering beneath the walls.',
    clues: [
      'The besieging army has vanished from the coast, leaving only a gift.',
      'Laocoön argued that this object must not be brought into the city.',
      'Warriors hidden inside will open the gates at night.',
    ],
    options: ['The Return of the Argonauts', 'The Trojan Horse', 'The War of the Giants', 'The Seven against Thebes'],
    reveal:
      'The wooden-horse ruse is the most famous story of Troy’s fall. Homer refers to it indirectly; Virgil’s Aeneid supplies the best-known extended account.',
    source: 'Homer — Odyssey VIII; Virgil — Aeneid II',
    sourceNote: 'The Trojan tradition contains Greek and Roman layers written centuries apart.',
    symbol: '♘',
  },
  {
    id: 'prometheus',
    title: 'Prometheus Steals Fire',
    eyebrow: 'Age of the Gods',
    cycle: 'Olympian Order',
    category: 'gods',
    location: 'Mount Olympus',
    coordinates: { lat: 40.0856, lng: 22.3586 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'The pin marks Mount Olympus, the dominant Greek location of the gods’ dwelling.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/491677',
    image: './assets/scene-prometheus.webp',
    fallback: 'linear-gradient(130deg, #11131a 0%, #49331f 48%, #e7772e 100%)',
    prompt: 'Track the hidden ember on Olympus, the hollow fennel stalk, and the eagle shape in the distant storm.',
    clues: [
      'The stolen object symbolises the beginning of human civilisation.',
      'The thief is a Titan who will be chained in the Caucasus.',
      'An eagle will consume his renewed liver each day.',
    ],
    options: ['The Fall of Hephaestus', 'Psyche’s Trials', 'Prometheus Steals Fire', 'The Birth of Dionysus'],
    reveal:
      'Prometheus restores fire to mortals by hiding an ember in a giant fennel stalk. His punishment answers both the theft and his challenge to Zeus’s new order.',
    source: 'Hesiod — Theogony and Works and Days',
    sourceNote: 'The Aeschylean tradition expands Prometheus into a founder of civilisation.',
    symbol: '△',
  },
  {
    id: 'apollo-python',
    title: 'Apollo and Python',
    eyebrow: 'Delphic Cycle',
    cycle: 'Olympian Order',
    category: 'gods',
    location: 'Delphi, Phocis',
    coordinates: { lat: 38.4824, lng: 22.501 },
    accuracyRadiusKm: 25,
    mapConfidence: 'attested',
    geographyNote: 'The pin marks the sanctuary of Delphi beneath the Phaedriades cliffs.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/540726',
    image: './assets/scene-apollo-python.webp',
    fallback: 'linear-gradient(128deg, #171512 0%, #665033 48%, #d4a853 100%)',
    prompt: 'Find the laurel, the omphalos, the bronze tripod, a lowered bow, and the serpent hidden among the rocks.',
    clues: [
      'The sanctuary will become the most famous oracle in the Greek world.',
      'The young god claims the site after confronting its great serpent guardian.',
      'His victory is remembered in the Pythian name of the oracle and games.',
    ],
    options: ['Apollo and Python', 'Cadmus and the Dragon', 'Heracles and Ladon', 'Zeus and Typhon'],
    reveal:
      'The Homeric Hymn to Apollo tells how Apollo established his Delphic sanctuary after defeating the serpent. The story explains the Pythian title attached to the oracle and its festival.',
    source: 'Homeric Hymn to Apollo 300–374; Apollodorus — Bibliotheca I.4.1',
    sourceNote: 'The sanctuary is real; the combat and its chronology belong to mythic aetiology.',
    symbol: '☀',
  },
  {
    id: 'cicones',
    title: 'Odysseus and the Cicones',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Ismaros, regional placement in Thrace',
    coordinates: { lat: 40.96, lng: 25.37 },
    accuracyRadiusKm: 40,
    mapConfidence: 'traditional',
    geographyNote: 'Homer names Ismaros, but its exact site remains unlocated; this pin marks the probable region near ancient Lake Ismaris.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/507409',
    image: './assets/scene-cicones.webp',
    fallback: 'linear-gradient(126deg, #17100d 0%, #76503a 47%, #d09a61 100%)',
    prompt: 'Find the overlong beach feast, Maron’s sealed wine jar, the beached ships, and reinforcements descending from the Thracian hills.',
    clues: [
      'After taking the city, the crew ignore the order to leave and continue feasting on the shore.',
      'A priest named Maron gives the traveller a powerful wine that will matter again inside a Cyclops’s cave.',
      'The people of this Thracian city fought as allies of Troy and return with inland reinforcements.',
    ],
    options: ['Odysseus and the Cicones', 'The Sack of Thebes', 'Jason at Lemnos', 'The Return of Menelaus'],
    reveal:
      'After leaving Troy, Odysseus sacks Ismaros but cannot make his crew depart. Reinforced Cicones drive the raiders back to sea, making this the voyage’s first costly failure of restraint.',
    source: 'Homer — Odyssey IX.39–66, 193–211',
    sourceNote: 'Ismaros is named in the poem, but the regional pin is approximate because the ancient city has not been securely located.',
    symbol: '⚔',
  },
  {
    id: 'lotus-eaters',
    title: 'Odysseus and the Lotus-Eaters',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Land of the Lotus-Eaters, traditional Djerba association',
    coordinates: { lat: 33.7833, lng: 10.8833 },
    accuracyRadiusKm: 60,
    mapConfidence: 'traditional',
    geographyNote: 'Homer supplies no secure coordinates; Djerba, known in antiquity as Lotophagitis, is a later traditional association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/344440',
    image: './assets/scene-lotus-eaters.webp',
    fallback: 'linear-gradient(124deg, #142016 0%, #62784d 46%, #d6a86a 100%)',
    prompt: 'Find the untouched travel gear, bowls of lotus fruit, dreamlike sailors, and companions pulling one man back toward the ship.',
    clues: [
      'The islanders are peaceful, but their food dissolves every desire to return home.',
      'The captain drags the affected scouts back by force and binds them beneath the rowing benches.',
      'This encounter follows the storm that drives the fleet away from Cape Malea.',
    ],
    options: ['Demeter at Eleusis', 'Odysseus and the Lotus-Eaters', 'Heracles in the Garden', 'Dionysus and the Pirates'],
    reveal:
      'The lotus does not kill Odysseus’s scouts; it makes them forget the purpose of their voyage. Odysseus forces them aboard before the rest of the crew can taste it.',
    source: 'Homer — Odyssey IX.82–104',
    sourceNote: 'The Djerba placement belongs to geographic tradition rather than a location established by Homer.',
    symbol: '✿',
  },
  {
    id: 'aeolus',
    title: 'Odysseus and Aeolus',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Aeolia, traditional Lipari association',
    coordinates: { lat: 38.467, lng: 14.957 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'Homer describes a floating, bronze-walled island; the Lipari Islands represent a later traditional association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/462284',
    image: './assets/scene-aeolus.webp',
    fallback: 'linear-gradient(126deg, #0b1622 0%, #384d69 47%, #bb7f4b 100%)',
    prompt: 'Find the oxhide bag and silver cord, the exhausted captain, the whispering crew, and Ithaca’s beacon behind the gathering storm.',
    clues: [
      'The keeper of the winds seals every dangerous wind inside an oxhide bag and leaves only the west wind free.',
      'Within sight of home, the crew mistake the closed gift for treasure and open it while their captain sleeps.',
      'The second arrival at the bronze-walled island ends in rejection rather than another rescue.',
    ],
    options: ['Odysseus and Aeolus', 'Poseidon and Minos', 'Boreas and Oreithyia', 'Jason and the Clashing Rocks'],
    reveal:
      'Aeolus gives Odysseus a bag containing the contrary winds. The suspicious crew open it almost at Ithaca, and the released storm carries the ship all the way back to Aeolia.',
    source: 'Homer — Odyssey X.1–79',
    sourceNote: 'Lipari is a traditional candidate for Aeolia; Homer’s marvellous floating island cannot be plotted as a historical site.',
    symbol: '≋',
  },
  {
    id: 'laestrygonians',
    title: 'Odysseus and the Laestrygonians',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Telepylus, traditional Formiae association',
    coordinates: { lat: 41.2557, lng: 13.6012 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'Homer’s Telepylus cannot be located securely; ancient and later tradition associated the episode with Formiae.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/432839',
    image: './assets/scene-laestrygonians.webp',
    fallback: 'linear-gradient(123deg, #07141b 0%, #35505b 48%, #936349 100%)',
    prompt: 'Look into the narrow calm harbour: the trapped fleet, boulders falling from the cliffs, and one cut cable leading toward open sea.',
    clues: [
      'All the captains except one moor inside a harbour enclosed by steep cliffs and a narrow entrance.',
      'The inhabitants are giant cannibals who destroy ships by hurling rocks from above.',
      'Only the vessel tied outside the harbour escapes when its captain cuts the cable.',
    ],
    options: ['The Giants against Olympus', 'Odysseus and the Laestrygonians', 'Heracles and Cacus', 'Perseus and Atlas'],
    reveal:
      'The Laestrygonians trap the fleet inside Telepylus and smash every ship but Odysseus’s with boulders. His caution in mooring outside the harbour saves the final vessel.',
    source: 'Homer — Odyssey X.80–132',
    sourceNote: 'Formiae is a traditional identification, not a securely recoverable coordinate for Homeric Telepylus.',
    symbol: '∩',
  },
  {
    id: 'polyphemus',
    title: 'Odysseus and Polyphemus',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'The Cyclopes’ Coast, traditional eastern Sicily',
    coordinates: { lat: 37.5633, lng: 15.1619 },
    accuracyRadiusKm: 40,
    mapConfidence: 'traditional',
    geographyNote: 'Homer does not name Sicily; the eastern Sicilian Cyclops coast is a later and influential geographic association.',
    image: './assets/scene-polyphemus.webp',
    fallback: 'linear-gradient(125deg, #0b0c0c 0%, #49382b 48%, #8b6a45 100%)',
    prompt: 'Search the immense cave for a giant wine bowl, a fire-hardened olive stake, and sailors hidden beneath rams.',
    clues: [
      'The traveller gives his captor wine and says that his name is Nobody.',
      'The cave entrance is sealed by a stone that only its giant owner can move.',
      'The survivors escape beneath the flock instead of walking beside it.',
    ],
    options: ['Theseus and the Minotaur', 'Odysseus and Polyphemus', 'Jason and the Harpies', 'Heracles and Cacus'],
    reveal:
      'Odysseus blinds the Cyclops after naming himself “Nobody,” then escapes by fastening his companions beneath Polyphemus’s rams. His later boast brings Poseidon’s anger upon the voyage.',
    source: 'Homer — Odyssey IX',
    sourceNote: 'The Sicilian location belongs to later geographic tradition rather than a precise coordinate supplied by Homer.',
    symbol: '◌',
  },
  {
    id: 'circe',
    title: 'Odysseus and Circe',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Aeaea, traditional Monte Circeo association',
    coordinates: { lat: 41.232, lng: 13.055 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'Aeaea is a mythic island without secure coordinates; Monte Circeo represents one long-lived Italian association.',
    image: './assets/scene-circe.webp',
    fallback: 'linear-gradient(126deg, #10130d 0%, #3e4a2b 46%, #b08c50 100%)',
    prompt: 'Find the loom, the herb-filled cup, tame lions and wolves, swine in the court, and the white moly flower.',
    clues: [
      'Hermes gives the traveller a white-flowered herb that protects him from the cup.',
      'The missing crew have not left the palace; their shapes have been changed.',
      'The enchantress later warns the crew about the Sirens and the two dangers of the strait.',
    ],
    options: ['Medea and the Argonauts', 'Calypso and Odysseus', 'Odysseus and Circe', 'Demeter and Metaneira'],
    reveal:
      'Circe transforms Odysseus’s companions into swine, but Hermes’s moly protects the hero from her potion. She restores the crew and later becomes their guide to the dangers ahead.',
    source: 'Homer — Odyssey X–XII',
    sourceNote: 'Ancient and later authors proposed several locations for Aeaea; none is historically certain.',
    symbol: '✺',
  },
  {
    id: 'scylla-charybdis',
    title: 'Scylla and Charybdis',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Strait of Messina, traditional placement',
    coordinates: { lat: 38.254, lng: 15.64 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'The Strait of Messina became the dominant ancient and later identification of Homer’s opposing sea dangers.',
    image: './assets/scene-scylla-charybdis.webp',
    fallback: 'linear-gradient(124deg, #07191d 0%, #285a62 48%, #b7a16d 100%)',
    prompt: 'Turn between the cliff’s many canine shadows and the enormous whirlpool pulling foam and driftwood from the opposite side.',
    clues: [
      'Circe warns that the ship cannot avoid both dangers completely.',
      'One threat lives high in a cave; the other swallows and releases the sea.',
      'Sailors still describe impossible choices as being caught between these two names.',
    ],
    options: ['The Symplegades', 'Poseidon and Minos', 'The Flood of Deucalion', 'Scylla and Charybdis'],
    reveal:
      'Odysseus steers closer to Scylla because Charybdis could destroy the entire ship. The passage costs six companions, making the episode one of the poem’s starkest choices between unequal disasters.',
    source: 'Homer — Odyssey XII',
    sourceNote: 'The Messina identification is traditional; Homer’s poetic geography does not function as a modern nautical chart.',
    symbol: '↯',
  },
  {
    id: 'underworld',
    title: 'Odysseus in the Underworld',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'The Land of the Dead, mapped through Ephyra / Acheron',
    coordinates: { lat: 39.236, lng: 20.534 },
    accuracyRadiusKm: 45,
    mapConfidence: 'mythic',
    geographyNote: 'Homer places the dead beyond Oceanus. The Acheron pin is a Greek ritual and geographic analogue, not a recoverable coordinate from the poem.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/531011',
    image: './assets/scene-underworld.webp',
    fallback: 'linear-gradient(126deg, #080b0c 0%, #263833 48%, #8b6841 100%)',
    prompt: 'Find the offering trench, the gathering shades, the unburied Elpenor, and the seer Tiresias approaching with a golden staff.',
    clues: [
      'The traveller pours milk, honey, wine, water, and blood into a trench so that the dead can speak.',
      'Tiresias foretells the dangers still waiting on the voyage and warns against harming the Sun’s cattle.',
      'Elpenor asks for burial, and the traveller also meets the shade of his mother Anticleia.',
    ],
    options: ['Orpheus and Eurydice', 'Odysseus in the Underworld', 'Heracles Captures Cerberus', 'Aeneas in the Underworld'],
    reveal:
      'Following Circe’s instructions, Odysseus crosses Oceanus and performs a rite for the dead. Tiresias reveals the conditions of the homeward voyage, while encounters with Elpenor, Anticleia, and fallen heroes turn the journey into a reckoning with memory and mortality.',
    source: 'Homer — Odyssey X.488–XI.640',
    sourceNote: 'Ephyra and the Acheron landscape provide a later Greek underworld analogue; they are not presented as Homer’s exact Land of the Dead.',
    symbol: 'Ψ',
  },
  {
    id: 'cattle-helios',
    title: 'Odysseus and the Cattle of Helios',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Thrinacia, traditional Sicily association',
    coordinates: { lat: 37.5896, lng: 14.0576 },
    accuracyRadiusKm: 60,
    mapConfidence: 'traditional',
    geographyNote: 'Homer names Thrinacia but does not securely identify it with Sicily; the island became a prominent ancient and later association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/462492',
    image: './assets/scene-cattle-helios.webp',
    fallback: 'linear-gradient(126deg, #15202a 0%, #6d5534 48%, #d2a647 100%)',
    prompt: 'Find the sacred white cattle, their divine guardians, an oath-breaking feast, and Zeus’s storm gathering beyond the beached ship.',
    clues: [
      'The herds belong to the Sun and must never be harmed, however long the crew remain trapped by bad weather.',
      'While their captain sleeps, the starving sailors sacrifice the finest animals and try to disguise the act as worship.',
      'Lampetia reports the crime; after the ship leaves, Zeus destroys it with a thunderbolt.',
    ],
    options: ['Jason and the Bronze Bulls', 'Heracles and Geryon', 'Odysseus and the Cattle of Helios', 'The Sacrifice at Aulis'],
    reveal:
      'Despite repeated warnings, Eurylochus persuades the starving crew to kill Helios’s sacred cattle. Zeus answers the Sun’s demand for justice by wrecking the ship, leaving Odysseus as the voyage’s sole survivor.',
    source: 'Homer — Odyssey XII.260–419',
    sourceNote: 'Sicily is a traditional identification of Thrinacia, not an uncontested coordinate in Homeric geography.',
    symbol: '☉',
  },
  {
    id: 'calypso',
    title: 'Odysseus and Calypso',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Ogygia, traditional Gozo association',
    coordinates: { lat: 36.0444, lng: 14.2512 },
    accuracyRadiusKm: 40,
    mapConfidence: 'traditional',
    geographyNote: 'Ogygia is a marvellous island without secure coordinates; Gozo is one long-lived Mediterranean candidate among several.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/462213',
    image: './assets/scene-calypso.webp',
    fallback: 'linear-gradient(126deg, #0c1d22 0%, #426f67 48%, #d3a866 100%)',
    prompt: 'Look around the island cave for a golden shuttle, four springs, Hermes’s message, a half-built raft, and a traveller grieving beside the sea.',
    clues: [
      'The immortal mistress of the island offers her guest ageless life, but he continues to long for home.',
      'Hermes arrives with Zeus’s command that the captive traveller must be released.',
      'After seven years, he fells trees and builds the raft that will carry him toward the Phaeacians.',
    ],
    options: ['Odysseus and Calypso', 'Theseus and Ariadne', 'Jason and Medea', 'Paris and Oenone'],
    reveal:
      'Calypso shelters Odysseus on Ogygia and offers him immortality, yet he chooses the uncertain mortal journey back to Ithaca. Only Zeus’s order, delivered by Hermes, finally compels her to help him leave.',
    source: 'Homer — Odyssey V',
    sourceNote: 'The Gozo association is traditional and contested; Homer’s Ogygia cannot be securely placed on a modern map.',
    symbol: '∞',
  },
  {
    id: 'phaeacians',
    title: 'Odysseus among the Phaeacians',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Scheria, traditional Corcyra association',
    coordinates: { lat: 39.62, lng: 19.8665 },
    accuracyRadiusKm: 45,
    mapConfidence: 'traditional',
    geographyNote: 'Scheria is not securely locatable; Corcyra, modern Corfu, became its dominant traditional Mediterranean association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/530835',
    image: './assets/scene-phaeacians.webp',
    fallback: 'linear-gradient(126deg, #10202a 0%, #577d75 48%, #d8b37b 100%)',
    prompt: 'Find Nausicaa’s laundry and ball, the castaway hidden among olive branches, the distant palace, and the swift ship prepared for his final passage.',
    clues: [
      'A princess and her attendants discover the shipwrecked stranger while washing clothes beside a river.',
      'At King Alcinous’s court, the bard Demodocus sings of Troy until the concealed guest begins to weep.',
      'The hosts carry the sleeping traveller home in a ship that knows its own way across the sea.',
    ],
    options: ['Perseus on Seriphos', 'Theseus on Naxos', 'Orestes in Tauris', 'Odysseus among the Phaeacians'],
    reveal:
      'Nausicaa’s kindness leads Odysseus to the court of Alcinous and Arete, where he finally tells the adventures that form much of the Odyssey. The Phaeacians then carry him, asleep, to Ithaca.',
    source: 'Homer — Odyssey VI–VIII; XIII.1–187',
    sourceNote: 'Corcyra is a traditional candidate for Scheria rather than a location established beyond dispute by the poem.',
    symbol: '⚓',
  },
  {
    id: 'homecoming',
    title: 'The Return of Odysseus',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Ithaca, traditional Homeric identification',
    coordinates: { lat: 38.4003, lng: 20.6928 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'The island of Ithaca is real and ancient; the poem’s palace and every detail of its landscape cannot be tied to one excavated spot.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/530906',
    image: './assets/scene-homecoming.webp',
    fallback: 'linear-gradient(126deg, #16140f 0%, #68513a 48%, #c69556 100%)',
    prompt: 'Find the beggar’s disguise, Penelope’s loom, the great bow, twelve aligned axe heads, and the living olive trunk built into the marriage bed.',
    clues: [
      'The returned king enters his own hall in disguise while only the old hound Argos recognises him at once.',
      'Penelope declares that she will marry whoever can string the absent king’s bow and shoot through twelve axe heads.',
      'A secret known only to husband and wife—their bed built around a rooted olive tree—proves his identity.',
    ],
    options: ['The Murder of Agamemnon', 'The Return of Odysseus', 'Orestes Avenges Agamemnon', 'The Return of Menelaus'],
    reveal:
      'Back on Ithaca, Odysseus tests allies and enemies before winning Penelope’s bow contest and revealing himself. The final recognition rests not on glory but on shared knowledge of the olive-root bed at the centre of their household.',
    source: 'Homer — Odyssey XVII–XXIII',
    sourceNote: 'The map marks ancient Ithaca, while the exact location and historicity of the poem’s palace remain debated.',
    symbol: '⌂',
  },
  {
    id: 'daphne',
    title: 'Apollo and Daphne',
    eyebrow: 'Metamorphoses',
    cycle: 'Age of the Gods',
    category: 'gods',
    location: 'Vale of Tempe, traditional Peneus association',
    coordinates: { lat: 39.876, lng: 22.5665 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'Ovid names the river-god Peneus as Daphne’s father. Tempe is a traditional Peneus landscape for the story, not an excavated event site.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/541131',
    image: './assets/scene-daphne.webp',
    fallback: 'linear-gradient(126deg, #1b2114 0%, #58704b 48%, #d3aa62 100%)',
    prompt: 'Find Cupid’s opposing arrows, the pursuing god’s abandoned bow, the river Peneus, and the nymph whose feet root as laurel rises around her.',
    clues: [
      'A golden arrow kindles desire in one god, while a leaden arrow makes the pursued nymph reject it.',
      'The nymph calls to her river-god father Peneus as the chase reaches its end.',
      'Her transformation explains why the laurel becomes sacred to Apollo and crowns poets and victors.',
    ],
    options: ['Pan and Syrinx', 'Zeus and Io', 'Apollo and Daphne', 'Hades and Persephone'],
    reveal:
      'After Apollo mocks Cupid’s bow, Cupid answers with two arrows: gold for desire and lead for aversion. Daphne escapes the pursuit through transformation into a laurel, which Apollo then claims as his sacred tree.',
    source: 'Ovid — Metamorphoses I.452–567',
    sourceNote: 'The fullest surviving version is Roman; the Tempe and Peneus placement is literary and traditional rather than archaeological.',
    symbol: '❧',
  },
  {
    id: 'echo',
    title: 'Echo and Narcissus',
    eyebrow: 'Metamorphoses',
    cycle: 'Boeotian Tales',
    category: 'gods',
    location: 'Thespiae and Mount Helicon, Boeotia',
    coordinates: { lat: 38.2935, lng: 23.1549 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'Ovid places the story broadly in Aonia, the poetic landscape of Boeotia. The pin marks Thespiae beneath Helicon, not an excavated event site.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/541141',
    image: './assets/scene-echo.webp',
    fallback: 'linear-gradient(126deg, #111610 0%, #4c5a42 48%, #b18d5f 100%)',
    prompt: 'Find the goddess being delayed, nymphs slipping into the woods, a hunter calling beside a still pool, and a hidden figure fading into stone.',
    clues: [
      'Hera limits a talkative mountain nymph to repeating only the final words spoken by someone else.',
      'The punishment follows a deception: long conversations gave Zeus’s companions time to escape.',
      'After Narcissus rejects her, her body wastes into rock and only the answering voice remains.',
    ],
    options: ['Echo and Narcissus', 'Apollo and Daphne', 'Orpheus and Eurydice', 'Pan and Syrinx'],
    reveal:
      'Echo distracts Hera with endless conversation while other nymphs escape. Hera answers by taking away her independent speech, leaving her only the last words she hears. After Narcissus rejects her, Echo fades until nothing remains but the returning voice that bears her name.',
    source: 'Ovid — Metamorphoses III.339–510',
    sourceNote: 'Ovid supplies the best-known surviving narrative. The ancient Greek name Ēkhō also personifies the natural phenomenon; the story is an aetiology, not a linguistic proof.',
    symbol: '↶',
  },
  {
    id: 'pegasus-birth',
    title: 'The Birth of Pegasus',
    eyebrow: 'Theogony',
    cycle: 'Perseus Cycle',
    category: 'heroes',
    location: 'The Gorgons’ Shore, mythic western Oceanus',
    coordinates: { lat: 35.9, lng: -7.2 },
    accuracyRadiusKm: 140,
    mapConfidence: 'mythic',
    geographyNote: 'Hesiod places the birth beside the springs of Oceanus at the world’s remote edge. This western pin visualises poetic direction, not historical geography.',
    image: './assets/scene-pegasus-birth.webp',
    fallback: 'linear-gradient(126deg, #0b1113 0%, #3e5050 48%, #b1935d 100%)',
    prompt: 'Find Perseus’s reflected shield, the springs of Oceanus, the first unfolding wings, and the golden brother born beside the horse.',
    clues: [
      'A white winged horse and the warrior Chrysaor spring forth at the instant Medusa is defeated.',
      'Hesiod connects the horse’s name with its birth beside the springs of Oceanus.',
      'The newborn creature later rises to Olympus and carries Zeus’s thunder and lightning.',
    ],
    options: ['The Horses of Diomedes', 'The Birth of Pegasus', 'Arion and Heracles', 'Bellerophon Tames Pegasus'],
    reveal:
      'When Perseus cuts down the mortal Gorgon, Pegasus and Chrysaor emerge together. Hesiod places the miraculous birth beside Oceanus; Pegasus later reaches Olympus before becoming inseparable from the story of Bellerophon.',
    source: 'Hesiod — Theogony 270–286; Apollodorus — Bibliotheca II.4.2',
    sourceNote: 'The western location is deliberately mythic, and ancient sources vary in the later sequence of Pegasus’s adventures.',
    symbol: '♧',
  },
  {
    id: 'chimera',
    title: 'Bellerophon and the Chimera',
    eyebrow: 'Lycian Cycle',
    cycle: 'Age of Heroes',
    category: 'heroes',
    location: 'Yanartaş / Mount Chimera, Lycia',
    coordinates: { lat: 36.4316, lng: 30.4561 },
    accuracyRadiusKm: 25,
    mapConfidence: 'traditional',
    geographyNote: 'Yanartaş is a real field of persistent gas flames. Its identification with the Chimera is an ancient and later geographic tradition, not proof that the combat occurred there.',
    image: './assets/scene-chimera.webp',
    fallback: 'linear-gradient(126deg, #080d12 0%, #293f43 48%, #c06b32 100%)',
    prompt: 'Find flames rising from bare rock, one creature with lion, goat, and serpent forms, a winged horse above, and a spear weighted for the fire.',
    clues: [
      'The monster combines a lion’s front, a goat rising from its body, and a serpent for a tail.',
      'King Iobates sends the hero into what should be an impossible battle in Lycia.',
      'Riding Pegasus, Bellerophon attacks from above; later tradition gives his spear a lead tip that melts in the creature’s fire.',
    ],
    options: ['Cadmus and the Dragon', 'Heracles and the Nemean Lion', 'Perseus and the Sea Monster', 'Bellerophon and the Chimera'],
    reveal:
      'Bellerophon survives Iobates’s deadly commission by attacking the fire-breathing Chimera from Pegasus. The natural flames of Yanartaş above the Lycian coast later became the landscape most powerfully associated with the monster.',
    source: 'Homer — Iliad VI.155–203; Hesiod — Theogony 319–325; Apollodorus — Bibliotheca II.3.1–2',
    sourceNote: 'The myth is ancient; the exact equation of its mountain with modern Yanartaş remains a traditional interpretation.',
    symbol: '♨',
  },
  {
    id: 'judgement-paris',
    title: 'The Judgement of Paris',
    eyebrow: 'Trojan Prelude',
    cycle: 'Trojan War',
    category: 'trojan',
    location: 'Mount Ida, the Troad',
    coordinates: { lat: 39.6927, lng: 26.8192 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'Mount Ida is a real and anciently attested mountain. The judgement itself belongs to the mythic prelude of the Trojan War.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/550592',
    image: './assets/scene-judgement-paris.webp',
    fallback: 'linear-gradient(126deg, #172018 0%, #5f6343 48%, #d5a665 100%)',
    prompt: 'Find one golden apple, three rival goddesses, Hermes’s staff, and a Trojan shepherd-prince weighing impossible promises.',
    clues: [
      'Strife turns the wedding of Peleus and Thetis into a contest by throwing a golden prize among the gods.',
      'Hermes leads Hera, Athena, and Aphrodite to a Trojan prince living as a shepherd on Mount Ida.',
      'The winning offer is not a kingdom or victory in war, but the hand of Helen.',
    ],
    options: ['The Judgement of Paris', 'Atalanta’s Race', 'Peleus and Thetis', 'Athena and Poseidon'],
    reveal:
      'Hera offers rule, Athena offers victory, and Aphrodite offers Helen. Paris awards the judgement to Aphrodite, turning a divine rivalry into the most famous prelude to the Trojan War.',
    source: 'Pseudo-Apollodorus — Epitome 3.2; Proclus — summary of the Cypria',
    sourceNote: 'The lost Cypria narrated the wider prelude. The surviving summaries and later compendium preserve versions that do not agree in every detail.',
    symbol: '◇',
  },
  {
    id: 'iphigenia-aulis',
    title: 'Iphigenia at Aulis',
    eyebrow: 'Trojan Prelude',
    cycle: 'Trojan War',
    category: 'trojan',
    location: 'Aulis, Boeotia',
    coordinates: { lat: 38.4303, lng: 23.5937 },
    accuracyRadiusKm: 25,
    mapConfidence: 'attested',
    geographyNote: 'Aulis is an attested ancient settlement associated with the expedition. The sacrifice and substitution belong to literary tradition.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/579889',
    image: './assets/scene-iphigenia-aulis.webp',
    fallback: 'linear-gradient(126deg, #101a25 0%, #4c5963 48%, #c69861 100%)',
    prompt: 'Find the motionless fleet, Artemis above the grove, a false bridal gathering, and the deer appearing at the altar.',
    clues: [
      'The entire Achaean fleet is trapped in harbour because no wind will carry it toward Troy.',
      'Agamemnon brings his daughter to the camp by pretending that she will marry Achilles.',
      'In one influential version, Artemis removes the girl and leaves a deer in her place.',
    ],
    options: ['Polyxena at Troy', 'The Daughters of Danaus', 'Iphigenia at Aulis', 'Alcestis and Admetus'],
    reveal:
      'Calchas says Artemis will release the fleet only after Agamemnon offers his daughter. Pseudo-Apollodorus preserves the version in which Artemis substitutes a deer and carries Iphigenia away.',
    source: 'Pseudo-Apollodorus — Epitome 3.21–22; Euripides — Iphigenia at Aulis',
    sourceNote: 'Ancient versions disagree over whether Iphigenia dies, is rescued, or is transformed into an immortal figure.',
    symbol: '☾',
  },
  {
    id: 'hector-andromache',
    title: 'Hector and Andromache',
    eyebrow: 'The Iliad · Book VI',
    cycle: 'The Iliad',
    category: 'trojan',
    location: 'The Scaean Gate, Ilion / Troy',
    coordinates: { lat: 39.9575, lng: 26.2389 },
    accuracyRadiusKm: 18,
    mapConfidence: 'attested',
    geographyNote: 'The archaeological mound is identified with ancient Ilion. The precise position and form of Homer’s Scaean Gate cannot be fixed.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/550595',
    image: './assets/scene-hector-andromache.webp',
    fallback: 'linear-gradient(126deg, #28221c 0%, #73583e 48%, #d9a866 100%)',
    prompt: 'Find a horsehair helmet set aside, a frightened infant, an open gate toward the war, and two parents who already understand the cost.',
    clues: [
      'The child recoils from the bronze helmet and its horsehair crest until his father removes it and laughs.',
      'The wife at the gate has already lost her father and brothers to Achilles.',
      'The warrior knows Troy may fall, yet says shame and duty will not let him remain behind the walls.',
    ],
    options: ['Odysseus and Penelope', 'Hector and Andromache', 'Menelaus and Helen', 'Orpheus and Eurydice'],
    reveal:
      'Hector removes his helmet, embraces Astyanax, and prays that his son may surpass him. Andromache’s plea cannot keep him from battle, making the scene a domestic farewell inside a war epic.',
    source: 'Homer — Iliad VI.369–502',
    sourceNote: 'The scene is Homeric; the visual reconstruction of Troy’s gate and clothing remains interpretive.',
    symbol: '♜',
  },
  {
    id: 'patroclus-falls',
    title: 'The Fall of Patroclus',
    eyebrow: 'The Iliad · Book XVI',
    cycle: 'The Iliad',
    category: 'trojan',
    location: 'The Trojan plain outside Ilion',
    coordinates: { lat: 39.943, lng: 26.262 },
    accuracyRadiusKm: 20,
    mapConfidence: 'traditional',
    geographyNote: 'The scene belongs to the plain around Troy, but the poem does not permit a modern pin for the exact point of combat.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/550595',
    image: './assets/scene-patroclus-falls.webp',
    fallback: 'linear-gradient(126deg, #171613 0%, #5b4932 48%, #c7894f 100%)',
    prompt: 'Find Achilles’ fallen helmet, armour coming loose under divine force, Euphorbus’s spear, and Hector closing the final distance.',
    clues: [
      'One warrior enters battle wearing the armour of his absent companion in order to save the Achaean ships.',
      'Apollo strikes from behind and sends the borrowed helmet rolling through the dust.',
      'Euphorbus wounds him first; Hector then deals the final blow that brings Achilles back into the war.',
    ],
    options: ['The Death of Sarpedon', 'Achilles at the River', 'The Fall of Patroclus', 'The Wounding of Menelaus'],
    reveal:
      'Patroclus drives the Trojans from the ships but ignores Achilles’ limit and presses toward Troy. Apollo strips away his advantage, Euphorbus wounds him, and Hector finishes the attack.',
    source: 'Homer — Iliad XVI.783–867',
    sourceNote: 'Homer distributes responsibility among a god and two mortal attackers rather than presenting a simple duel.',
    symbol: '⬙',
  },
  {
    id: 'achilles-hector',
    title: 'Achilles and Hector',
    eyebrow: 'The Iliad · Book XXII',
    cycle: 'The Iliad',
    category: 'trojan',
    location: 'Outside the walls of Ilion / Troy',
    coordinates: { lat: 39.953, lng: 26.248 },
    accuracyRadiusKm: 18,
    mapConfidence: 'traditional',
    geographyNote: 'The duel is placed outside Troy’s walls near the Scaean Gate and springs, whose exact Homeric topography is debated.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/550595',
    image: './assets/scene-achilles-hector.webp',
    fallback: 'linear-gradient(126deg, #171715 0%, #6f5436 48%, #d7a251 100%)',
    prompt: 'Find the two springs, armour shining like fire, a deceptive brother who will vanish, and golden scales tipping in the storm.',
    clues: [
      'The pursued defender circles his own city three times before turning to face his enemy.',
      'Athena takes the likeness of Deiphobus and makes him believe that his brother will fight beside him.',
      'Zeus weighs two fates in golden scales before the Pelian spear decides the duel.',
    ],
    options: ['Ajax and Hector', 'Diomedes and Ares', 'Menelaus and Paris', 'Achilles and Hector'],
    reveal:
      'After three circuits of Troy, Hector stands when Athena deceives him in the form of Deiphobus. Achilles finds the vulnerable point in the armour Hector had taken from Patroclus.',
    source: 'Homer — Iliad XXII.131–366',
    sourceNote: 'The scene is a fatal duel, but Homer frames it through fear, deception, grief, and fate rather than uncomplicated heroism.',
    symbol: '⚔',
  },
  {
    id: 'priam-achilles',
    title: 'Priam and Achilles',
    eyebrow: 'The Iliad · Book XXIV',
    cycle: 'The Iliad',
    category: 'trojan',
    location: 'The Achaean camp on the coast below Troy',
    coordinates: { lat: 39.95, lng: 26.17 },
    accuracyRadiusKm: 25,
    mapConfidence: 'traditional',
    geographyNote: 'The Achaean camp belongs to the coast below Troy. Bronze Age shorelines and Homeric camp topography do not yield one secure modern coordinate.',
    image: './assets/scene-priam-achilles.webp',
    fallback: 'linear-gradient(126deg, #10131a 0%, #4e3a2b 48%, #b77d45 100%)',
    prompt: 'Find a king kneeling in an enemy hut, ransom gifts, a covered bier, and a meal waiting after two enemies weep together.',
    clues: [
      'An old king enters the enemy camp with Hermes as guide and kisses the hands of the man who killed his son.',
      'He asks Achilles to remember his own father, Peleus, and grief breaks the warrior’s rage.',
      'The ransom returns Hector’s body and creates the truce that closes the Iliad.',
    ],
    options: ['Agamemnon and Chryses', 'Priam and Achilles', 'Phoenix and Achilles', 'Nestor and Telemachus'],
    reveal:
      'Priam’s appeal makes Achilles think of Peleus while both men mourn different dead. Achilles accepts the ransom, returns Hector, and grants time for the funeral—the act of mercy with which the Iliad ends.',
    source: 'Homer — Iliad XXIV.468–676',
    sourceNote: 'The Trojan Horse and the fall of the city occur later in the epic cycle; the Iliad itself ends with Hector’s funeral.',
    symbol: '✧',
  },
  {
    id: 'orpheus-eurydice',
    title: 'Orpheus and Eurydice',
    eyebrow: 'Orphic Cycle',
    cycle: 'Love and the Underworld',
    category: 'heroes',
    location: 'The Taenarian Gate, Cape Tainaron',
    coordinates: { lat: 36.3972, lng: 22.4772 },
    accuracyRadiusKm: 20,
    mapConfidence: 'traditional',
    geographyNote: 'Ovid names a Taenarian gate into the Underworld. The pin marks the Cape Tainaron cave tradition, not a recoverable route to a literal underworld.',
    image: './assets/scene-orpheus-eurydice.webp',
    fallback: 'linear-gradient(128deg, #0c1116 0%, #34424a 48%, #b08a5b 100%)',
    prompt: 'Find the lyre, the fading bride, the listening shades, and the daylight that is almost within reach.',
    clues: [
      'A musician’s song has moved the rulers of the dead to grant one impossible return.',
      'The condition is simple: he must not turn to look behind him until both have reached the upper world.',
      'At the final threshold, doubt overcomes Orpheus and Eurydice is lost a second time.',
    ],
    options: ['Alcestis and Admetus', 'Orpheus and Eurydice', 'Pygmalion and Galatea', 'Psyche in the Underworld'],
    reveal:
      'Orpheus wins Eurydice’s release through music, but looks back just before they reach daylight. Ovid explicitly sends him down through the Taenarian gate and makes his anxious love the cause of the second loss.',
    source: 'Virgil — Georgics IV.453–527; Ovid — Metamorphoses X.1–85',
    sourceNote: 'The famous backward glance is developed most fully in Roman-period literary versions of an older Greek tradition.',
    symbol: '♫',
  },
  {
    id: 'oedipus-sphinx',
    title: 'Oedipus and the Sphinx',
    eyebrow: 'Theban Cycle',
    cycle: 'The House of Laius',
    category: 'heroes',
    location: 'Mount Phicium, near Thebes',
    coordinates: { lat: 38.3719, lng: 23.185 },
    accuracyRadiusKm: 18,
    mapConfidence: 'traditional',
    geographyNote: 'Apollodorus names Mount Phicium. Its proposed modern identification near Thebes is low-confidence, so this pin visualises the literary landscape rather than a secure site.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/541138',
    image: './assets/scene-oedipus-sphinx.webp',
    fallback: 'linear-gradient(126deg, #231c16 0%, #7c5c3c 48%, #d5a566 100%)',
    prompt: 'Study the traveller’s staff, the winged lioness, the road into Thebes, and the changing tracks in the dust.',
    clues: [
      'The creature asks what has one voice but walks on four, then two, then three supports.',
      'The answer is humankind: crawling in infancy, walking upright in adulthood, and leaning on a staff in age.',
      'Solving the riddle wins Oedipus the throne of Thebes, but also carries him deeper into the fate he tried to escape.',
    ],
    options: ['Oedipus and the Sphinx', 'Perseus and the Gorgons', 'Cadmus and the Dragon', 'Bellerophon and the Chimera'],
    reveal:
      'Oedipus answers that the Sphinx’s changing creature is a human being. Thebes is freed, but his reward—the kingship and marriage to the widowed queen—unknowingly fulfils the oracle he fled.',
    source: 'Apollodorus — Bibliotheca III.5.8; Sophocles — Oedipus Tyrannus',
    sourceNote: 'The riddle episode precedes the action of Sophocles’ tragedy; Apollodorus preserves a compact narrative version.',
    symbol: '?',
  },
  {
    id: 'lernaean-hydra',
    title: 'Heracles and the Lernaean Hydra',
    eyebrow: 'Labours of Heracles',
    cycle: 'Age of Heroes',
    category: 'heroes',
    location: 'Lerna, Argolis',
    coordinates: { lat: 37.5511, lng: 22.7184 },
    accuracyRadiusKm: 18,
    mapConfidence: 'attested',
    geographyNote: 'The pin marks the excavated Bronze Age settlement and wetland landscape of Lerna; the many-headed creature belongs to myth.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/570424',
    image: './assets/scene-lernaean-hydra.webp',
    fallback: 'linear-gradient(126deg, #101811 0%, #45533b 46%, #aa733c 100%)',
    prompt: 'Find the lion skin, the regenerating serpent heads, the burning brands, the hidden crab, and a waiting chariot.',
    clues: [
      'Every mortal head struck down grows back as two unless its root is burned.',
      'Iolaus assists with fire, while a giant crab sent by Hera attacks the hero’s foot.',
      'Eurystheus refuses to count this labour because Heracles did not complete it alone.',
    ],
    options: ['Jason and the Colchian Dragon', 'Apollo and Python', 'Heracles and the Lernaean Hydra', 'Zeus and Typhon'],
    reveal:
      'Heracles cannot defeat regeneration with force alone. Iolaus burns each neck after it is cut, the immortal head is buried beneath a rock, and Hydra’s venom is taken for the hero’s arrows.',
    source: 'Apollodorus — Bibliotheca II.5.2; Hesiod — Theogony 313–318',
    sourceNote: 'Ancient sources vary on the number of heads; Apollodorus gives nine, including one immortal head.',
    symbol: '♆',
  },
  {
    id: 'midas-gold',
    title: 'Midas and the Golden Touch',
    eyebrow: 'Phrygian Cycle',
    cycle: 'Kings and Consequences',
    category: 'heroes',
    location: 'Gordion, Phrygia',
    coordinates: { lat: 39.6503, lng: 31.9785 },
    accuracyRadiusKm: 22,
    mapConfidence: 'traditional',
    geographyNote: 'Gordion is the attested Phrygian capital traditionally associated with Midas. Ovid does not locate the first transformation there and places the cure at the Pactolus near Sardis.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/609393',
    image: './assets/scene-midas-gold.webp',
    fallback: 'linear-gradient(126deg, #2a1510 0%, #8d4f2c 44%, #d7a533 100%)',
    prompt: 'Look past the riches: untouched bread, wine, branches, and stone are becoming the same useless metal.',
    clues: [
      'Dionysus grants a reward after the king returns the wandering Silenus.',
      'At first every transformed object seems miraculous, until food and drink harden before they can be consumed.',
      'The king must wash the power away in the Pactolus, explaining the river’s legendary golden sands.',
    ],
    options: ['Tantalus Tests the Gods', 'The Treasure of Polycrates', 'Croesus at Delphi', 'Midas and the Golden Touch'],
    reveal:
      'Midas asks Dionysus to make everything he touches turn to gold. Hunger and thirst expose the gift as a curse, and the god tells him to wash it away in the Pactolus.',
    source: 'Ovid — Metamorphoses XI.85–145',
    sourceNote: 'The daughter transformed into gold is a much later addition and is deliberately absent from this scene.',
    symbol: '◆',
  },
  {
    id: 'apollo-marsyas',
    title: 'Apollo and Marsyas',
    eyebrow: 'Phrygian Cycle',
    cycle: 'Music and Hubris',
    category: 'gods',
    location: 'Kelainai / Celaenae, Phrygia',
    coordinates: { lat: 38.0701, lng: 30.1716 },
    accuracyRadiusKm: 18,
    mapConfidence: 'traditional',
    geographyNote: 'Kelainai is an attested Phrygian city. Herodotus and Xenophon explicitly connect its river spring and cave with Marsyas, while the musical contest itself remains mythic tradition.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/638751',
    image: './assets/scene-apollo-marsyas.webp',
    fallback: 'linear-gradient(126deg, #242015 0%, #6c5836 46%, #c69b59 100%)',
    prompt: 'Find the double pipes, the kithara, the spring cave, the silent judges, and two musicians whose contest cannot end as equals.',
    clues: [
      'A discarded double aulos associated with Athena becomes the instrument of a Phrygian challenger.',
      'The opponent is the god of the lyre, music, prophecy, and the Delphic bow.',
      'Ancient visitors to Kelainai were shown the river cave and a grim local relic said to preserve the contest’s aftermath.',
    ],
    options: ['Pan and Apollo', 'Orpheus before Hades', 'Apollo and Marsyas', 'Athena and Arachne'],
    reveal:
      'Marsyas challenges Apollo to a musical contest with the double aulos against the god’s kithara. The challenger loses and pays a brutal penalty; the scene stops before that violence and instead anchors the tradition in the spring landscape of Kelainai.',
    source: 'Apollodorus — Bibliotheca I.4.2; Herodotus — Histories VII.26; Ovid — Metamorphoses VI.382–400',
    sourceNote: 'Ancient accounts disagree about the judges and the precise contest rules. Herodotus records the local Phrygian tradition at Kelainai rather than treating the event as history.',
    symbol: '♭',
  },
  {
    id: 'niobe-sipylus',
    title: 'Niobe’s Tears',
    eyebrow: 'Lydian Cycle',
    cycle: 'Divine Retribution',
    category: 'gods',
    location: 'Mount Sipylus above Magnesia, Lydia',
    coordinates: { lat: 38.567, lng: 27.456 },
    accuracyRadiusKm: 18,
    mapConfidence: 'traditional',
    geographyNote: 'Mount Sipylus is an attested Anatolian landmark. Homer, Apollodorus, and Pausanias connect Niobe’s enduring stone and tears with this mountain, but no single rock can prove a mythic transformation.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/550884',
    image: './assets/scene-niobe-sipylus.webp',
    fallback: 'linear-gradient(126deg, #20231f 0%, #696955 46%, #b89159 100%)',
    prompt: 'Find the grieving queen becoming mountain stone, the flowing tears, the lowered divine bows, and the empty emblems of a family lost to pride.',
    clues: [
      'A queen boasts that her many children make her more fortunate than the mother of Apollo and Artemis.',
      'The divine twins answer the insult with arrows, though ancient authors disagree about the number of children and survivors.',
      'After the catastrophe, the mother returns to Sipylus and becomes a stone that continues to weep.',
    ],
    options: ['Arachne and Athena', 'The Daughters of Danaus', 'Niobe’s Tears', 'Ariadne Abandoned'],
    reveal:
      'Niobe compares herself with Leto, and Apollo and Artemis destroy her children. Apollodorus sends the grieving mother back to her father Tantalus at Sipylus, where Zeus transforms her into a stone whose tears never cease.',
    source: 'Homer — Iliad XXIV.602–617; Apollodorus — Bibliotheca III.5.6; Pausanias — Description of Greece I.21.3',
    sourceNote: 'The number of Niobe’s children varies sharply between ancient sources. The panorama avoids choosing one count and shows no deaths.',
    symbol: '◌',
  },
  {
    id: 'selene-endymion',
    title: 'Selene and Endymion',
    eyebrow: 'Carian Cycle',
    cycle: 'Moon and Mortal',
    category: 'gods',
    location: 'Mount Latmos above Heraclea, Caria',
    coordinates: { lat: 37.5018, lng: 27.525 },
    accuracyRadiusKm: 22,
    mapConfidence: 'traditional',
    geographyNote: 'Heraclea beneath Mount Latmos is an attested Carian city. Local tradition honoured Endymion on the mountain; other Greek communities claimed different biographies and burial places.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/599640',
    image: './assets/scene-selene-endymion.webp',
    fallback: 'linear-gradient(126deg, #09121d 0%, #28394a 48%, #b7a16f 100%)',
    prompt: 'Find the moonlit cave, the sleeping shepherd-prince, the pale horses, the untouched staff, and a night that seems unable to end.',
    clues: [
      'A mortal of surpassing beauty is loved by the personified Moon.',
      'Given a choice by Zeus, he asks to remain deathless and ageless in unending sleep.',
      'The people of Heraclea said he withdrew to Mount Latmos, where they maintained his sanctuary.',
    ],
    options: ['Eos and Tithonus', 'Selene and Endymion', 'Aphrodite and Adonis', 'Hypnos and Pasithea'],
    reveal:
      'Selene falls in love with Endymion, who chooses eternal youth in everlasting sleep. The most famous landscape of their story is a cave on Carian Mount Latmos, though Elis preserved a competing tradition.',
    source: 'Apollodorus — Bibliotheca I.7.5; Pausanias — Description of Greece V.1.5; Strabo — Geography XIV.1.8',
    sourceNote: 'The sources combine several Endymion traditions: shepherd, prince, king, astronomer, Latmian sleeper, and Elean ancestor.',
    symbol: '☾',
  },
  {
    id: 'hylas-nymphs',
    title: 'Hylas and the Nymphs',
    eyebrow: 'The Argonautica',
    cycle: 'Voyage of the Argo',
    category: 'heroes',
    location: 'The Mysian coast near Kios, Bithynia',
    coordinates: { lat: 40.4325, lng: 29.1564 },
    accuracyRadiusKm: 20,
    mapConfidence: 'traditional',
    geographyNote: 'Kios is an attested harbour on the Propontis. Apollonius places Hylas’s disappearance in the surrounding Mysian spring landscape, not at a recoverable modern fountain.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/511385',
    image: './assets/scene-hylas-nymphs.webp',
    fallback: 'linear-gradient(126deg, #07151b 0%, #244a4b 47%, #a37c4f 100%)',
    prompt: 'Find the bronze water jar, the moonlit spring, the nymph rising from its reflection, the searching hero, and the Argo preparing to leave.',
    clues: [
      'A young companion leaves the Argonaut camp carrying a bronze vessel to fetch water for the evening meal.',
      'A spring nymph sees him in the full moon and draws him into the water.',
      'Heracles searches the Mysian woods so long that the Argo sails without them.',
    ],
    options: ['Narcissus at the Pool', 'Hermaphroditus and Salmacis', 'Hylas and the Nymphs', 'Actaeon and Artemis'],
    reveal:
      'Hylas reaches a spring called Pegae while the nymphs gather for Artemis. A water nymph pulls him beneath the surface, leaving Heracles and Polyphemus searching as the Argonauts depart.',
    source: 'Apollonius Rhodius — Argonautica I.1207–1272; Apollodorus — Bibliotheca I.9.19',
    sourceNote: 'Later traditions connect the Mysian search ritual and the foundation of Kios with the disappearance. The scene presents a mysterious abduction without violence.',
    symbol: '♒',
  },
]

export type AtlasPlace = Point & {
  name: string
  gameName?: { en: string; tr: string }
  type: string
  period: string
  confidence: MapConfidence
  pleiadesUrl?: string
}

export const atlasPlaces: AtlasPlace[] = [
  { name: 'Olympus', lat: 40.0856, lng: 22.3586, type: 'Gods', period: 'Mythic landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/491677' },
  { name: 'Delphi', lat: 38.4824, lng: 22.501, type: 'Oracle', period: 'Archaic–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/540726' },
  { name: 'Athens', lat: 37.9715, lng: 23.7267, type: 'Polis', period: 'Bronze Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/579885' },
  { name: 'Knossos', lat: 35.2989, lng: 25.1603, type: 'Heroes', period: 'Bronze Age', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/589872' },
  { name: 'Ilion / Troy', lat: 39.9575, lng: 26.2389, type: 'War', period: 'Bronze Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/550595' },
  { name: 'Ithaca', lat: 38.4003, lng: 20.6928, type: 'Odyssey', period: 'Homeric landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/530906' },
  { name: 'Thebes', lat: 38.3192, lng: 23.3176, type: 'Tragedy', period: 'Bronze Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/541138' },
  { name: 'Mycenae', lat: 37.7308, lng: 22.7561, type: 'Kings', period: 'Bronze Age', confidence: 'attested' },
  { name: 'Corinth', lat: 37.9056, lng: 22.8797, type: 'Polis', period: 'Archaic–Roman', confidence: 'attested' },
  { name: 'Delos', lat: 37.4009, lng: 25.2674, type: 'Sanctuary', period: 'Archaic–Roman', confidence: 'attested' },
  { name: 'Sparta', lat: 37.0755, lng: 22.4303, type: 'Polis', period: 'Archaic–Roman', confidence: 'attested' },
  { name: 'Tainaron', lat: 36.3972, lng: 22.4772, type: 'Underworld', period: 'Mythic landscape', confidence: 'traditional' },
  { name: 'Ismaros / Cicones', gameName: { en: 'Ismaros', tr: 'Ismaros' }, lat: 40.96, lng: 25.37, type: 'Odyssey', period: 'Homeric regional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/507409' },
  { name: 'Djerba / Lotophagitis', gameName: { en: 'Djerba', tr: 'Cerbe' }, lat: 33.7833, lng: 10.8833, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/344440' },
  { name: 'Cyclopes’ Coast', gameName: { en: 'Eastern Sicily', tr: 'Doğu Sicilya' }, lat: 37.5633, lng: 15.1619, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional' },
  { name: 'Lipari / Aeolia', gameName: { en: 'Lipari', tr: 'Lipari' }, lat: 38.467, lng: 14.957, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/462284' },
  { name: 'Formiae / Telepylus', gameName: { en: 'Formiae', tr: 'Formiae' }, lat: 41.2557, lng: 13.6012, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/432839' },
  { name: 'Aeaea / Circeo', gameName: { en: 'Latian Coast', tr: 'Latium Kıyısı' }, lat: 41.232, lng: 13.055, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional' },
  { name: 'Ephyra / Acheron', gameName: { en: 'Ephyra', tr: 'Ephyra' }, lat: 39.236, lng: 20.534, type: 'Odyssey', period: 'Underworld analogue', confidence: 'mythic', pleiadesUrl: 'https://pleiades.stoa.org/places/531011' },
  { name: 'Messina Strait', lat: 38.254, lng: 15.64, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional' },
  { name: 'Sicilia / Thrinacia', gameName: { en: 'Central Sicily', tr: 'Orta Sicilya' }, lat: 37.5896, lng: 14.0576, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/462492' },
  { name: 'Gozo / Ogygia', gameName: { en: 'Gozo', tr: 'Gozo' }, lat: 36.0444, lng: 14.2512, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/462213' },
  { name: 'Corcyra / Scheria', gameName: { en: 'Corcyra', tr: 'Korkyra' }, lat: 39.62, lng: 19.8665, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/530835' },
  { name: 'Tempe / Daphne', gameName: { en: 'Tempe Valley', tr: 'Tempe Vadisi' }, lat: 39.876, lng: 22.5665, type: 'Gods', period: 'Literary landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/541131' },
  { name: 'Thespiae / Echo', gameName: { en: 'Thespiae', tr: 'Thespiai' }, lat: 38.2935, lng: 23.1549, type: 'Metamorphosis', period: 'Literary landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/541141' },
  { name: 'Gorgons’ Shore / Pegasus', gameName: { en: 'Far Western Ocean', tr: 'Uzak Batı Okeanosu' }, lat: 35.9, lng: -7.2, type: 'Heroes', period: 'Mythic direction', confidence: 'mythic' },
  { name: 'Yanartaş / Chimera', gameName: { en: 'Yanartaş', tr: 'Yanartaş' }, lat: 36.4316, lng: 30.4561, type: 'Heroes', period: 'Traditional placement', confidence: 'traditional' },
  { name: 'Mount Ida / Paris', gameName: { en: 'Mount Ida', tr: 'İda Dağı' }, lat: 39.6927, lng: 26.8192, type: 'Trojan Prelude', period: 'Ancient mountain', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/550592' },
  { name: 'Aulis / Iphigenia', gameName: { en: 'Aulis', tr: 'Aulis' }, lat: 38.4303, lng: 23.5937, type: 'Trojan Prelude', period: 'Bronze Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/579889' },
  { name: 'Mount Phicium? / Sphinx', gameName: { en: 'Mount Phicium?', tr: 'Phikion Dağı?' }, lat: 38.3719, lng: 23.185, type: 'Theban Cycle', period: 'Low-confidence literary placement', confidence: 'traditional' },
  { name: 'Lerna / Hydra', gameName: { en: 'Lerna', tr: 'Lerna' }, lat: 37.5511, lng: 22.7184, type: 'Heroes', period: 'Bronze Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/570424' },
  { name: 'Gordion / Midas', gameName: { en: 'Gordion', tr: 'Gordion' }, lat: 39.6503, lng: 31.9785, type: 'Phrygian Cycle', period: 'Iron Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/609393' },
  { name: 'Kelainai / Marsyas', gameName: { en: 'Kelainai', tr: 'Kelainai' }, lat: 38.0701, lng: 30.1716, type: 'Phrygian Cycle', period: 'Phrygian–Roman', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/638751' },
  { name: 'Sipylos / Niobe', gameName: { en: 'Mount Sipylus', tr: 'Sipylos Dağı' }, lat: 38.567, lng: 27.456, type: 'Lydian Cycle', period: 'Ancient mountain', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/550884' },
  { name: 'Latmos / Endymion', gameName: { en: 'Mount Latmos', tr: 'Latmos Dağı' }, lat: 37.5018, lng: 27.525, type: 'Carian Cycle', period: 'Carian–Roman', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/599640' },
  { name: 'Kios / Hylas', gameName: { en: 'Kios', tr: 'Kios' }, lat: 40.4325, lng: 29.1564, type: 'Argonautica', period: 'Archaic–Roman', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/511385' },
]

export const ancientRegions: Array<Point & { name: string; kind: 'land' | 'sea' }> = [
  { name: 'MAGNA GRAECIA', lat: 38.9, lng: 16.2, kind: 'land' },
  { name: 'HELLAS', lat: 39.2, lng: 22.4, kind: 'land' },
  { name: 'MACEDONIA', lat: 41.05, lng: 22.7, kind: 'land' },
  { name: 'THRACE', lat: 41.75, lng: 27.0, kind: 'land' },
  { name: 'ASIA MINOR', lat: 38.8, lng: 31.0, kind: 'land' },
  { name: 'CRETE', lat: 35.15, lng: 24.6, kind: 'land' },
  { name: 'LYCIA', lat: 36.8, lng: 29.7, kind: 'land' },
  { name: 'AEGEAN SEA', lat: 38.3, lng: 25.2, kind: 'sea' },
  { name: 'IONIAN SEA', lat: 37.4, lng: 18.7, kind: 'sea' },
  { name: 'SICILIA', lat: 37.6, lng: 13.7, kind: 'land' },
]

export const odysseyRoute: Point[] = [
  { lat: 39.9575, lng: 26.2389 },
  { lat: 40.96, lng: 25.37 },
  { lat: 33.7833, lng: 10.8833 },
  { lat: 37.5633, lng: 15.1619 },
  { lat: 38.467, lng: 14.957 },
  { lat: 41.2557, lng: 13.6012 },
  { lat: 41.232, lng: 13.055 },
  { lat: 39.236, lng: 20.534 },
  { lat: 40.5808, lng: 14.4296 },
  { lat: 38.254, lng: 15.64 },
  { lat: 37.5896, lng: 14.0576 },
  { lat: 36.0444, lng: 14.2512 },
  { lat: 39.62, lng: 19.8665 },
  { lat: 38.4003, lng: 20.6928 },
]

export const collections = [
  {
    title: 'Olympians',
    count: 15,
    note: 'Power, jealousy, and sacred order',
    color: '#bf8e42',
    art: './assets/scene-prometheus.webp',
  },
  {
    title: 'Heroes',
    count: 19,
    note: 'Mortals who pay the price of victory',
    color: '#94422d',
    art: './assets/scene-medusa.webp',
  },
  {
    title: 'Creatures',
    count: 14,
    note: 'Beasts, hybrids, and beings beyond mortal order',
    color: '#53624c',
    art: './assets/scene-labyrinth.webp',
  },
  {
    title: 'Trojan Cycle',
    count: 10,
    note: 'One war, hundreds of destinies',
    color: '#71503c',
    art: './assets/scene-trojan-horse.webp',
  },
]
