export type Point = { lat: number; lng: number }

export type MapConfidence = 'attested' | 'traditional' | 'mythic'
export type MythCategory = 'gods' | 'heroes' | 'odyssey' | 'trojan'

export type MythScene = {
  id: string
  title: string
  eyebrow: string
  cycle: string
  category: MythCategory
  location: string
  coordinates: Point
  accuracyRadiusKm: number
  mapConfidence: MapConfidence
  geographyNote: string
  pleiadesUrl?: string
  image: string
  fallback: string
  prompt: string
  clues: string[]
  options: string[]
  reveal: string
  source: string
  sourceNote: string
  symbol: string
}

export const mythScenes: MythScene[] = [
  {
    id: 'labyrinth',
    title: 'Theseus and the Minotaur',
    eyebrow: 'Cretan Cycle',
    cycle: 'Age of Heroes',
    category: 'heroes',
    location: 'Knossos, Crete',
    coordinates: { lat: 35.2989, lng: 25.1603 },
    accuracyRadiusKm: 30,
    mapConfidence: 'attested',
    geographyNote: 'The myth is associated with Knossos; the archaeological palace is not literally the maze of the story.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/589872',
    image: './assets/scene-labyrinth.webp',
    fallback: 'linear-gradient(118deg, #13110d 0%, #4e2b1e 44%, #a56136 100%)',
    prompt: 'Find the double axes on the walls, the distant horned shadow, and the red thread crossing the floor.',
    clues: [
      'The thread was left so that its bearer could find the way out again.',
      'This palace belongs to the island ruled by King Minos.',
      'The creature is half man and half bull.',
    ],
    options: ['Orpheus and Eurydice', 'Theseus and the Minotaur', 'Heracles and the Hydra', 'Bellerophon and the Chimera'],
    reveal:
      'With Ariadne’s thread, Theseus escapes the labyrinth designed by Daedalus. The myth is tied to Knossos, although the excavated palace and the legendary maze are not the same thing.',
    source: 'Apollodorus — Bibliotheca; Plutarch — Theseus',
    sourceNote: 'Ancient versions disagree on several details.',
    symbol: '𐂂',
  },
  {
    id: 'medusa',
    title: 'Perseus and Medusa',
    eyebrow: 'Perseus Cycle',
    cycle: 'Age of Heroes',
    category: 'heroes',
    location: 'The far western edge of Oceanus',
    coordinates: { lat: 35.9, lng: -7.2 },
    accuracyRadiusKm: 140,
    mapConfidence: 'mythic',
    geographyNote: 'Ancient poetry places the Gorgons in the distant west; this pin visualises a mythic direction, not an excavated site.',
    image: './assets/scene-medusa.webp',
    fallback: 'linear-gradient(120deg, #101713 0%, #31453d 45%, #a09878 100%)',
    prompt: 'Do not look directly. Petrified warriors and a mirror-bright shield should be enough.',
    clues: [
      'The hero watches his target only through a reflection in his shield.',
      'Athena gave him a polished shield; Hermes supplied a curved blade.',
      'The monster’s hair is made of living snakes.',
    ],
    options: ['Apollo and Python', 'Cadmus and the Dragon', 'Perseus and Medusa', 'Odysseus and Polyphemus'],
    reveal:
      'Perseus uses the polished shield as a mirror to avoid Medusa’s gaze. Ancient authors place the Gorgons near the remote western boundary of the imagined world.',
    source: 'Hesiod — Theogony; Apollodorus — Bibliotheca II',
    sourceNote: 'The map pin is an explicitly mythic placement, not a claim of historical precision.',
    symbol: '◉',
  },
  {
    id: 'sirens',
    title: 'Odysseus and the Sirens',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'The Siren Rocks, traditional Campanian placement',
    coordinates: { lat: 40.5808, lng: 14.4296 },
    accuracyRadiusKm: 45,
    mapConfidence: 'traditional',
    geographyNote: 'Homer gives no secure coordinates; later tradition often identifies the Sirens with islands off Campania.',
    image: './assets/scene-sirens.webp',
    fallback: 'linear-gradient(132deg, #071c24 0%, #22616a 48%, #e0a45e 100%)',
    prompt: 'Study the storm-dark water, the wax-sealed ears, and the traveller bound to the mast.',
    clues: [
      'The crew’s ears have been sealed with beeswax.',
      'The captain wants to hear the song, so he has himself tied to the mast.',
      'This happens during the voyage home from Troy to Ithaca.',
    ],
    options: ['Jason and the Harpies', 'Theseus and Ariadne', 'The Fall of Phaethon', 'Odysseus and the Sirens'],
    reveal:
      'Following Circe’s warning, Odysseus seals his crew’s ears with wax and has himself bound to the mast. He hears the Sirens and survives.',
    source: 'Homer — Odyssey XII',
    sourceNote: 'The exact location of the Sirens changes across ancient and modern interpretations.',
    symbol: '≈',
  },
  {
    id: 'trojan-horse',
    title: 'The Trojan Horse',
    eyebrow: 'Trojan Cycle',
    cycle: 'Trojan War',
    category: 'trojan',
    location: 'Ilion / Troy, Anatolia',
    coordinates: { lat: 39.9575, lng: 26.2389 },
    accuracyRadiusKm: 25,
    mapConfidence: 'attested',
    geographyNote: 'The pin marks the archaeological mound at Hisarlık, identified with ancient Ilion/Troy.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/550595',
    image: './assets/scene-trojan-horse.webp',
    fallback: 'linear-gradient(126deg, #17130f 0%, #744425 49%, #df9b4d 100%)',
    prompt: 'Look for the open gates at dawn, the abandoned shore, and the immense wooden offering beneath the walls.',
    clues: [
      'The besieging army has vanished from the coast, leaving only a gift.',
      'Laocoön argued that this object must not be brought into the city.',
      'Warriors hidden inside will open the gates at night.',
    ],
    options: ['The Return of the Argonauts', 'The Trojan Horse', 'The War of the Giants', 'The Seven against Thebes'],
    reveal:
      'The wooden-horse ruse is the most famous story of Troy’s fall. Homer refers to it indirectly; Virgil’s Aeneid supplies the best-known extended account.',
    source: 'Homer — Odyssey VIII; Virgil — Aeneid II',
    sourceNote: 'The Trojan tradition contains Greek and Roman layers written centuries apart.',
    symbol: '♘',
  },
  {
    id: 'prometheus',
    title: 'Prometheus Steals Fire',
    eyebrow: 'Age of the Gods',
    cycle: 'Olympian Order',
    category: 'gods',
    location: 'Mount Olympus',
    coordinates: { lat: 40.0856, lng: 22.3586 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'The pin marks Mount Olympus, the dominant Greek location of the gods’ dwelling.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/491677',
    image: './assets/scene-prometheus.webp',
    fallback: 'linear-gradient(130deg, #11131a 0%, #49331f 48%, #e7772e 100%)',
    prompt: 'Track the hidden ember on Olympus, the hollow fennel stalk, and the eagle shape in the distant storm.',
    clues: [
      'The stolen object symbolises the beginning of human civilisation.',
      'The thief is a Titan who will be chained in the Caucasus.',
      'An eagle will consume his renewed liver each day.',
    ],
    options: ['The Fall of Hephaestus', 'Psyche’s Trials', 'Prometheus Steals Fire', 'The Birth of Dionysus'],
    reveal:
      'Prometheus restores fire to mortals by hiding an ember in a giant fennel stalk. His punishment answers both the theft and his challenge to Zeus’s new order.',
    source: 'Hesiod — Theogony and Works and Days',
    sourceNote: 'The Aeschylean tradition expands Prometheus into a founder of civilisation.',
    symbol: '△',
  },
  {
    id: 'apollo-python',
    title: 'Apollo and Python',
    eyebrow: 'Delphic Cycle',
    cycle: 'Olympian Order',
    category: 'gods',
    location: 'Delphi, Phocis',
    coordinates: { lat: 38.4824, lng: 22.501 },
    accuracyRadiusKm: 25,
    mapConfidence: 'attested',
    geographyNote: 'The pin marks the sanctuary of Delphi beneath the Phaedriades cliffs.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/540726',
    image: './assets/scene-apollo-python.webp',
    fallback: 'linear-gradient(128deg, #171512 0%, #665033 48%, #d4a853 100%)',
    prompt: 'Find the laurel, the omphalos, the bronze tripod, a lowered bow, and the serpent hidden among the rocks.',
    clues: [
      'The sanctuary will become the most famous oracle in the Greek world.',
      'The young god claims the site after confronting its great serpent guardian.',
      'His victory is remembered in the Pythian name of the oracle and games.',
    ],
    options: ['Apollo and Python', 'Cadmus and the Dragon', 'Heracles and Ladon', 'Zeus and Typhon'],
    reveal:
      'The Homeric Hymn to Apollo tells how Apollo established his Delphic sanctuary after defeating the serpent. The story explains the Pythian title attached to the oracle and its festival.',
    source: 'Homeric Hymn to Apollo 300–374; Apollodorus — Bibliotheca I.4.1',
    sourceNote: 'The sanctuary is real; the combat and its chronology belong to mythic aetiology.',
    symbol: '☀',
  },
  {
    id: 'cicones',
    title: 'Odysseus and the Cicones',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Ismaros, regional placement in Thrace',
    coordinates: { lat: 40.96, lng: 25.37 },
    accuracyRadiusKm: 40,
    mapConfidence: 'traditional',
    geographyNote: 'Homer names Ismaros, but its exact site remains unlocated; this pin marks the probable region near ancient Lake Ismaris.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/507409',
    image: './assets/scene-cicones.webp',
    fallback: 'linear-gradient(126deg, #17100d 0%, #76503a 47%, #d09a61 100%)',
    prompt: 'Find the overlong beach feast, Maron’s sealed wine jar, the beached ships, and reinforcements descending from the Thracian hills.',
    clues: [
      'After taking the city, the crew ignore the order to leave and continue feasting on the shore.',
      'A priest named Maron gives the traveller a powerful wine that will matter again inside a Cyclops’s cave.',
      'The people of this Thracian city fought as allies of Troy and return with inland reinforcements.',
    ],
    options: ['Odysseus and the Cicones', 'The Sack of Thebes', 'Jason at Lemnos', 'The Return of Menelaus'],
    reveal:
      'After leaving Troy, Odysseus sacks Ismaros but cannot make his crew depart. Reinforced Cicones drive the raiders back to sea, making this the voyage’s first costly failure of restraint.',
    source: 'Homer — Odyssey IX.39–66, 193–211',
    sourceNote: 'Ismaros is named in the poem, but the regional pin is approximate because the ancient city has not been securely located.',
    symbol: '⚔',
  },
  {
    id: 'lotus-eaters',
    title: 'Odysseus and the Lotus-Eaters',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Land of the Lotus-Eaters, traditional Djerba association',
    coordinates: { lat: 33.7833, lng: 10.8833 },
    accuracyRadiusKm: 60,
    mapConfidence: 'traditional',
    geographyNote: 'Homer supplies no secure coordinates; Djerba, known in antiquity as Lotophagitis, is a later traditional association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/344440',
    image: './assets/scene-lotus-eaters.webp',
    fallback: 'linear-gradient(124deg, #142016 0%, #62784d 46%, #d6a86a 100%)',
    prompt: 'Find the untouched travel gear, bowls of lotus fruit, dreamlike sailors, and companions pulling one man back toward the ship.',
    clues: [
      'The islanders are peaceful, but their food dissolves every desire to return home.',
      'The captain drags the affected scouts back by force and binds them beneath the rowing benches.',
      'This encounter follows the storm that drives the fleet away from Cape Malea.',
    ],
    options: ['Demeter at Eleusis', 'Odysseus and the Lotus-Eaters', 'Heracles in the Garden', 'Dionysus and the Pirates'],
    reveal:
      'The lotus does not kill Odysseus’s scouts; it makes them forget the purpose of their voyage. Odysseus forces them aboard before the rest of the crew can taste it.',
    source: 'Homer — Odyssey IX.82–104',
    sourceNote: 'The Djerba placement belongs to geographic tradition rather than a location established by Homer.',
    symbol: '✿',
  },
  {
    id: 'aeolus',
    title: 'Odysseus and Aeolus',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Aeolia, traditional Lipari association',
    coordinates: { lat: 38.467, lng: 14.957 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'Homer describes a floating, bronze-walled island; the Lipari Islands represent a later traditional association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/462284',
    image: './assets/scene-aeolus.webp',
    fallback: 'linear-gradient(126deg, #0b1622 0%, #384d69 47%, #bb7f4b 100%)',
    prompt: 'Find the oxhide bag and silver cord, the exhausted captain, the whispering crew, and Ithaca’s beacon behind the gathering storm.',
    clues: [
      'The keeper of the winds seals every dangerous wind inside an oxhide bag and leaves only the west wind free.',
      'Within sight of home, the crew mistake the closed gift for treasure and open it while their captain sleeps.',
      'The second arrival at the bronze-walled island ends in rejection rather than another rescue.',
    ],
    options: ['Odysseus and Aeolus', 'Poseidon and Minos', 'Boreas and Oreithyia', 'Jason and the Clashing Rocks'],
    reveal:
      'Aeolus gives Odysseus a bag containing the contrary winds. The suspicious crew open it almost at Ithaca, and the released storm carries the ship all the way back to Aeolia.',
    source: 'Homer — Odyssey X.1–79',
    sourceNote: 'Lipari is a traditional candidate for Aeolia; Homer’s marvellous floating island cannot be plotted as a historical site.',
    symbol: '≋',
  },
  {
    id: 'laestrygonians',
    title: 'Odysseus and the Laestrygonians',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Telepylus, traditional Formiae association',
    coordinates: { lat: 41.2557, lng: 13.6012 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'Homer’s Telepylus cannot be located securely; ancient and later tradition associated the episode with Formiae.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/432839',
    image: './assets/scene-laestrygonians.webp',
    fallback: 'linear-gradient(123deg, #07141b 0%, #35505b 48%, #936349 100%)',
    prompt: 'Look into the narrow calm harbour: the trapped fleet, boulders falling from the cliffs, and one cut cable leading toward open sea.',
    clues: [
      'All the captains except one moor inside a harbour enclosed by steep cliffs and a narrow entrance.',
      'The inhabitants are giant cannibals who destroy ships by hurling rocks from above.',
      'Only the vessel tied outside the harbour escapes when its captain cuts the cable.',
    ],
    options: ['The Giants against Olympus', 'Odysseus and the Laestrygonians', 'Heracles and Cacus', 'Perseus and Atlas'],
    reveal:
      'The Laestrygonians trap the fleet inside Telepylus and smash every ship but Odysseus’s with boulders. His caution in mooring outside the harbour saves the final vessel.',
    source: 'Homer — Odyssey X.80–132',
    sourceNote: 'Formiae is a traditional identification, not a securely recoverable coordinate for Homeric Telepylus.',
    symbol: '∩',
  },
  {
    id: 'polyphemus',
    title: 'Odysseus and Polyphemus',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'The Cyclopes’ Coast, traditional eastern Sicily',
    coordinates: { lat: 37.5633, lng: 15.1619 },
    accuracyRadiusKm: 40,
    mapConfidence: 'traditional',
    geographyNote: 'Homer does not name Sicily; the eastern Sicilian Cyclops coast is a later and influential geographic association.',
    image: './assets/scene-polyphemus.webp',
    fallback: 'linear-gradient(125deg, #0b0c0c 0%, #49382b 48%, #8b6a45 100%)',
    prompt: 'Search the immense cave for a giant wine bowl, a fire-hardened olive stake, and sailors hidden beneath rams.',
    clues: [
      'The traveller gives his captor wine and says that his name is Nobody.',
      'The cave entrance is sealed by a stone that only its giant owner can move.',
      'The survivors escape beneath the flock instead of walking beside it.',
    ],
    options: ['Theseus and the Minotaur', 'Odysseus and Polyphemus', 'Jason and the Harpies', 'Heracles and Cacus'],
    reveal:
      'Odysseus blinds the Cyclops after naming himself “Nobody,” then escapes by fastening his companions beneath Polyphemus’s rams. His later boast brings Poseidon’s anger upon the voyage.',
    source: 'Homer — Odyssey IX',
    sourceNote: 'The Sicilian location belongs to later geographic tradition rather than a precise coordinate supplied by Homer.',
    symbol: '◌',
  },
  {
    id: 'circe',
    title: 'Odysseus and Circe',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Aeaea, traditional Monte Circeo association',
    coordinates: { lat: 41.232, lng: 13.055 },
    accuracyRadiusKm: 35,
    mapConfidence: 'traditional',
    geographyNote: 'Aeaea is a mythic island without secure coordinates; Monte Circeo represents one long-lived Italian association.',
    image: './assets/scene-circe.webp',
    fallback: 'linear-gradient(126deg, #10130d 0%, #3e4a2b 46%, #b08c50 100%)',
    prompt: 'Find the loom, the herb-filled cup, tame lions and wolves, swine in the court, and the white moly flower.',
    clues: [
      'Hermes gives the traveller a white-flowered herb that protects him from the cup.',
      'The missing crew have not left the palace; their shapes have been changed.',
      'The enchantress later warns the crew about the Sirens and the two dangers of the strait.',
    ],
    options: ['Medea and the Argonauts', 'Calypso and Odysseus', 'Odysseus and Circe', 'Demeter and Metaneira'],
    reveal:
      'Circe transforms Odysseus’s companions into swine, but Hermes’s moly protects the hero from her potion. She restores the crew and later becomes their guide to the dangers ahead.',
    source: 'Homer — Odyssey X–XII',
    sourceNote: 'Ancient and later authors proposed several locations for Aeaea; none is historically certain.',
    symbol: '✺',
  },
  {
    id: 'scylla-charybdis',
    title: 'Scylla and Charybdis',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Strait of Messina, traditional placement',
    coordinates: { lat: 38.254, lng: 15.64 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'The Strait of Messina became the dominant ancient and later identification of Homer’s opposing sea dangers.',
    image: './assets/scene-scylla-charybdis.webp',
    fallback: 'linear-gradient(124deg, #07191d 0%, #285a62 48%, #b7a16d 100%)',
    prompt: 'Turn between the cliff’s many canine shadows and the enormous whirlpool pulling foam and driftwood from the opposite side.',
    clues: [
      'Circe warns that the ship cannot avoid both dangers completely.',
      'One threat lives high in a cave; the other swallows and releases the sea.',
      'Sailors still describe impossible choices as being caught between these two names.',
    ],
    options: ['The Symplegades', 'Poseidon and Minos', 'The Flood of Deucalion', 'Scylla and Charybdis'],
    reveal:
      'Odysseus steers closer to Scylla because Charybdis could destroy the entire ship. The passage costs six companions, making the episode one of the poem’s starkest choices between unequal disasters.',
    source: 'Homer — Odyssey XII',
    sourceNote: 'The Messina identification is traditional; Homer’s poetic geography does not function as a modern nautical chart.',
    symbol: '↯',
  },
  {
    id: 'underworld',
    title: 'Odysseus in the Underworld',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'The Land of the Dead, mapped through Ephyra / Acheron',
    coordinates: { lat: 39.236, lng: 20.534 },
    accuracyRadiusKm: 45,
    mapConfidence: 'mythic',
    geographyNote: 'Homer places the dead beyond Oceanus. The Acheron pin is a Greek ritual and geographic analogue, not a recoverable coordinate from the poem.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/531011',
    image: './assets/scene-underworld.webp',
    fallback: 'linear-gradient(126deg, #080b0c 0%, #263833 48%, #8b6841 100%)',
    prompt: 'Find the offering trench, the gathering shades, the unburied Elpenor, and the seer Tiresias approaching with a golden staff.',
    clues: [
      'The traveller pours milk, honey, wine, water, and blood into a trench so that the dead can speak.',
      'Tiresias foretells the dangers still waiting on the voyage and warns against harming the Sun’s cattle.',
      'Elpenor asks for burial, and the traveller also meets the shade of his mother Anticleia.',
    ],
    options: ['Orpheus and Eurydice', 'Odysseus in the Underworld', 'Heracles Captures Cerberus', 'Aeneas in the Underworld'],
    reveal:
      'Following Circe’s instructions, Odysseus crosses Oceanus and performs a rite for the dead. Tiresias reveals the conditions of the homeward voyage, while encounters with Elpenor, Anticleia, and fallen heroes turn the journey into a reckoning with memory and mortality.',
    source: 'Homer — Odyssey X.488–XI.640',
    sourceNote: 'Ephyra and the Acheron landscape provide a later Greek underworld analogue; they are not presented as Homer’s exact Land of the Dead.',
    symbol: 'Ψ',
  },
  {
    id: 'cattle-helios',
    title: 'Odysseus and the Cattle of Helios',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Thrinacia, traditional Sicily association',
    coordinates: { lat: 37.5896, lng: 14.0576 },
    accuracyRadiusKm: 60,
    mapConfidence: 'traditional',
    geographyNote: 'Homer names Thrinacia but does not securely identify it with Sicily; the island became a prominent ancient and later association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/462492',
    image: './assets/scene-cattle-helios.webp',
    fallback: 'linear-gradient(126deg, #15202a 0%, #6d5534 48%, #d2a647 100%)',
    prompt: 'Find the sacred white cattle, their divine guardians, an oath-breaking feast, and Zeus’s storm gathering beyond the beached ship.',
    clues: [
      'The herds belong to the Sun and must never be harmed, however long the crew remain trapped by bad weather.',
      'While their captain sleeps, the starving sailors sacrifice the finest animals and try to disguise the act as worship.',
      'Lampetia reports the crime; after the ship leaves, Zeus destroys it with a thunderbolt.',
    ],
    options: ['Jason and the Bronze Bulls', 'Heracles and Geryon', 'Odysseus and the Cattle of Helios', 'The Sacrifice at Aulis'],
    reveal:
      'Despite repeated warnings, Eurylochus persuades the starving crew to kill Helios’s sacred cattle. Zeus answers the Sun’s demand for justice by wrecking the ship, leaving Odysseus as the voyage’s sole survivor.',
    source: 'Homer — Odyssey XII.260–419',
    sourceNote: 'Sicily is a traditional identification of Thrinacia, not an uncontested coordinate in Homeric geography.',
    symbol: '☉',
  },
  {
    id: 'calypso',
    title: 'Odysseus and Calypso',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Ogygia, traditional Gozo association',
    coordinates: { lat: 36.0444, lng: 14.2512 },
    accuracyRadiusKm: 40,
    mapConfidence: 'traditional',
    geographyNote: 'Ogygia is a marvellous island without secure coordinates; Gozo is one long-lived Mediterranean candidate among several.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/462213',
    image: './assets/scene-calypso.webp',
    fallback: 'linear-gradient(126deg, #0c1d22 0%, #426f67 48%, #d3a866 100%)',
    prompt: 'Look around the island cave for a golden shuttle, four springs, Hermes’s message, a half-built raft, and a traveller grieving beside the sea.',
    clues: [
      'The immortal mistress of the island offers her guest ageless life, but he continues to long for home.',
      'Hermes arrives with Zeus’s command that the captive traveller must be released.',
      'After seven years, he fells trees and builds the raft that will carry him toward the Phaeacians.',
    ],
    options: ['Odysseus and Calypso', 'Theseus and Ariadne', 'Jason and Medea', 'Paris and Oenone'],
    reveal:
      'Calypso shelters Odysseus on Ogygia and offers him immortality, yet he chooses the uncertain mortal journey back to Ithaca. Only Zeus’s order, delivered by Hermes, finally compels her to help him leave.',
    source: 'Homer — Odyssey V',
    sourceNote: 'The Gozo association is traditional and contested; Homer’s Ogygia cannot be securely placed on a modern map.',
    symbol: '∞',
  },
  {
    id: 'phaeacians',
    title: 'Odysseus among the Phaeacians',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Scheria, traditional Corcyra association',
    coordinates: { lat: 39.62, lng: 19.8665 },
    accuracyRadiusKm: 45,
    mapConfidence: 'traditional',
    geographyNote: 'Scheria is not securely locatable; Corcyra, modern Corfu, became its dominant traditional Mediterranean association.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/530835',
    image: './assets/scene-phaeacians.webp',
    fallback: 'linear-gradient(126deg, #10202a 0%, #577d75 48%, #d8b37b 100%)',
    prompt: 'Find Nausicaa’s laundry and ball, the castaway hidden among olive branches, the distant palace, and the swift ship prepared for his final passage.',
    clues: [
      'A princess and her attendants discover the shipwrecked stranger while washing clothes beside a river.',
      'At King Alcinous’s court, the bard Demodocus sings of Troy until the concealed guest begins to weep.',
      'The hosts carry the sleeping traveller home in a ship that knows its own way across the sea.',
    ],
    options: ['Perseus on Seriphos', 'Theseus on Naxos', 'Orestes in Tauris', 'Odysseus among the Phaeacians'],
    reveal:
      'Nausicaa’s kindness leads Odysseus to the court of Alcinous and Arete, where he finally tells the adventures that form much of the Odyssey. The Phaeacians then carry him, asleep, to Ithaca.',
    source: 'Homer — Odyssey VI–VIII; XIII.1–187',
    sourceNote: 'Corcyra is a traditional candidate for Scheria rather than a location established beyond dispute by the poem.',
    symbol: '⚓',
  },
  {
    id: 'homecoming',
    title: 'The Return of Odysseus',
    eyebrow: 'The Odyssey',
    cycle: 'After Troy',
    category: 'odyssey',
    location: 'Ithaca, traditional Homeric identification',
    coordinates: { lat: 38.4003, lng: 20.6928 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'The island of Ithaca is real and ancient; the poem’s palace and every detail of its landscape cannot be tied to one excavated spot.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/530906',
    image: './assets/scene-homecoming.webp',
    fallback: 'linear-gradient(126deg, #16140f 0%, #68513a 48%, #c69556 100%)',
    prompt: 'Find the beggar’s disguise, Penelope’s loom, the great bow, twelve aligned axe heads, and the living olive trunk built into the marriage bed.',
    clues: [
      'The returned king enters his own hall in disguise while only the old hound Argos recognises him at once.',
      'Penelope declares that she will marry whoever can string the absent king’s bow and shoot through twelve axe heads.',
      'A secret known only to husband and wife—their bed built around a rooted olive tree—proves his identity.',
    ],
    options: ['The Murder of Agamemnon', 'The Return of Odysseus', 'Orestes Avenges Agamemnon', 'The Return of Menelaus'],
    reveal:
      'Back on Ithaca, Odysseus tests allies and enemies before winning Penelope’s bow contest and revealing himself. The final recognition rests not on glory but on shared knowledge of the olive-root bed at the centre of their household.',
    source: 'Homer — Odyssey XVII–XXIII',
    sourceNote: 'The map marks ancient Ithaca, while the exact location and historicity of the poem’s palace remain debated.',
    symbol: '⌂',
  },
  {
    id: 'daphne',
    title: 'Apollo and Daphne',
    eyebrow: 'Metamorphoses',
    cycle: 'Age of the Gods',
    category: 'gods',
    location: 'Vale of Tempe, traditional Peneus association',
    coordinates: { lat: 39.876, lng: 22.5665 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'Ovid names the river-god Peneus as Daphne’s father. Tempe is a traditional Peneus landscape for the story, not an excavated event site.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/541131',
    image: './assets/scene-daphne.webp',
    fallback: 'linear-gradient(126deg, #1b2114 0%, #58704b 48%, #d3aa62 100%)',
    prompt: 'Find Cupid’s opposing arrows, the pursuing god’s abandoned bow, the river Peneus, and the nymph whose feet root as laurel rises around her.',
    clues: [
      'A golden arrow kindles desire in one god, while a leaden arrow makes the pursued nymph reject it.',
      'The nymph calls to her river-god father Peneus as the chase reaches its end.',
      'Her transformation explains why the laurel becomes sacred to Apollo and crowns poets and victors.',
    ],
    options: ['Pan and Syrinx', 'Zeus and Io', 'Apollo and Daphne', 'Hades and Persephone'],
    reveal:
      'After Apollo mocks Cupid’s bow, Cupid answers with two arrows: gold for desire and lead for aversion. Daphne escapes the pursuit through transformation into a laurel, which Apollo then claims as his sacred tree.',
    source: 'Ovid — Metamorphoses I.452–567',
    sourceNote: 'The fullest surviving version is Roman; the Tempe and Peneus placement is literary and traditional rather than archaeological.',
    symbol: '❧',
  },
  {
    id: 'echo',
    title: 'Echo and Narcissus',
    eyebrow: 'Metamorphoses',
    cycle: 'Boeotian Tales',
    category: 'gods',
    location: 'Thespiae and Mount Helicon, Boeotia',
    coordinates: { lat: 38.2935, lng: 23.1549 },
    accuracyRadiusKm: 30,
    mapConfidence: 'traditional',
    geographyNote: 'Ovid places the story broadly in Aonia, the poetic landscape of Boeotia. The pin marks Thespiae beneath Helicon, not an excavated event site.',
    pleiadesUrl: 'https://pleiades.stoa.org/places/541141',
    image: './assets/scene-echo.webp',
    fallback: 'linear-gradient(126deg, #111610 0%, #4c5a42 48%, #b18d5f 100%)',
    prompt: 'Find the goddess being delayed, nymphs slipping into the woods, a hunter calling beside a still pool, and a hidden figure fading into stone.',
    clues: [
      'Hera limits a talkative mountain nymph to repeating only the final words spoken by someone else.',
      'The punishment follows a deception: long conversations gave Zeus’s companions time to escape.',
      'After Narcissus rejects her, her body wastes into rock and only the answering voice remains.',
    ],
    options: ['Echo and Narcissus', 'Apollo and Daphne', 'Orpheus and Eurydice', 'Pan and Syrinx'],
    reveal:
      'Echo distracts Hera with endless conversation while other nymphs escape. Hera answers by taking away her independent speech, leaving her only the last words she hears. After Narcissus rejects her, Echo fades until nothing remains but the returning voice that bears her name.',
    source: 'Ovid — Metamorphoses III.339–510',
    sourceNote: 'Ovid supplies the best-known surviving narrative. The ancient Greek name Ēkhō also personifies the natural phenomenon; the story is an aetiology, not a linguistic proof.',
    symbol: '↶',
  },
  {
    id: 'pegasus-birth',
    title: 'The Birth of Pegasus',
    eyebrow: 'Theogony',
    cycle: 'Perseus Cycle',
    category: 'heroes',
    location: 'The Gorgons’ Shore, mythic western Oceanus',
    coordinates: { lat: 35.9, lng: -7.2 },
    accuracyRadiusKm: 140,
    mapConfidence: 'mythic',
    geographyNote: 'Hesiod places the birth beside the springs of Oceanus at the world’s remote edge. This western pin visualises poetic direction, not historical geography.',
    image: './assets/scene-pegasus-birth.webp',
    fallback: 'linear-gradient(126deg, #0b1113 0%, #3e5050 48%, #b1935d 100%)',
    prompt: 'Find Perseus’s reflected shield, the springs of Oceanus, the first unfolding wings, and the golden brother born beside the horse.',
    clues: [
      'A white winged horse and the warrior Chrysaor spring forth at the instant Medusa is defeated.',
      'Hesiod connects the horse’s name with its birth beside the springs of Oceanus.',
      'The newborn creature later rises to Olympus and carries Zeus’s thunder and lightning.',
    ],
    options: ['The Horses of Diomedes', 'The Birth of Pegasus', 'Arion and Heracles', 'Bellerophon Tames Pegasus'],
    reveal:
      'When Perseus cuts down the mortal Gorgon, Pegasus and Chrysaor emerge together. Hesiod places the miraculous birth beside Oceanus; Pegasus later reaches Olympus before becoming inseparable from the story of Bellerophon.',
    source: 'Hesiod — Theogony 270–286; Apollodorus — Bibliotheca II.4.2',
    sourceNote: 'The western location is deliberately mythic, and ancient sources vary in the later sequence of Pegasus’s adventures.',
    symbol: '♧',
  },
  {
    id: 'chimera',
    title: 'Bellerophon and the Chimera',
    eyebrow: 'Lycian Cycle',
    cycle: 'Age of Heroes',
    category: 'heroes',
    location: 'Yanartaş / Mount Chimera, Lycia',
    coordinates: { lat: 36.4316, lng: 30.4561 },
    accuracyRadiusKm: 25,
    mapConfidence: 'traditional',
    geographyNote: 'Yanartaş is a real field of persistent gas flames. Its identification with the Chimera is an ancient and later geographic tradition, not proof that the combat occurred there.',
    image: './assets/scene-chimera.webp',
    fallback: 'linear-gradient(126deg, #080d12 0%, #293f43 48%, #c06b32 100%)',
    prompt: 'Find flames rising from bare rock, one creature with lion, goat, and serpent forms, a winged horse above, and a spear weighted for the fire.',
    clues: [
      'The monster combines a lion’s front, a goat rising from its body, and a serpent for a tail.',
      'King Iobates sends the hero into what should be an impossible battle in Lycia.',
      'Riding Pegasus, Bellerophon attacks from above; later tradition gives his spear a lead tip that melts in the creature’s fire.',
    ],
    options: ['Cadmus and the Dragon', 'Heracles and the Nemean Lion', 'Perseus and the Sea Monster', 'Bellerophon and the Chimera'],
    reveal:
      'Bellerophon survives Iobates’s deadly commission by attacking the fire-breathing Chimera from Pegasus. The natural flames of Yanartaş above the Lycian coast later became the landscape most powerfully associated with the monster.',
    source: 'Homer — Iliad VI.155–203; Hesiod — Theogony 319–325; Apollodorus — Bibliotheca II.3.1–2',
    sourceNote: 'The myth is ancient; the exact equation of its mountain with modern Yanartaş remains a traditional interpretation.',
    symbol: '♨',
  },
]

export type AtlasPlace = Point & {
  name: string
  type: string
  period: string
  confidence: MapConfidence
  pleiadesUrl?: string
}

export const atlasPlaces: AtlasPlace[] = [
  { name: 'Olympus', lat: 40.0856, lng: 22.3586, type: 'Gods', period: 'Mythic landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/491677' },
  { name: 'Delphi', lat: 38.4824, lng: 22.501, type: 'Oracle', period: 'Archaic–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/540726' },
  { name: 'Athens', lat: 37.9715, lng: 23.7267, type: 'Polis', period: 'Bronze Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/579885' },
  { name: 'Knossos', lat: 35.2989, lng: 25.1603, type: 'Heroes', period: 'Bronze Age', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/589872' },
  { name: 'Ilion / Troy', lat: 39.9575, lng: 26.2389, type: 'War', period: 'Bronze Age–Roman', confidence: 'attested', pleiadesUrl: 'https://pleiades.stoa.org/places/550595' },
  { name: 'Ithaca', lat: 38.4003, lng: 20.6928, type: 'Odyssey', period: 'Homeric landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/530906' },
  { name: 'Thebes', lat: 38.3192, lng: 23.3176, type: 'Tragedy', period: 'Bronze Age–Roman', confidence: 'attested' },
  { name: 'Mycenae', lat: 37.7308, lng: 22.7561, type: 'Kings', period: 'Bronze Age', confidence: 'attested' },
  { name: 'Corinth', lat: 37.9056, lng: 22.8797, type: 'Polis', period: 'Archaic–Roman', confidence: 'attested' },
  { name: 'Delos', lat: 37.4009, lng: 25.2674, type: 'Sanctuary', period: 'Archaic–Roman', confidence: 'attested' },
  { name: 'Sparta', lat: 37.0755, lng: 22.4303, type: 'Polis', period: 'Archaic–Roman', confidence: 'attested' },
  { name: 'Tainaron', lat: 36.3972, lng: 22.4772, type: 'Underworld', period: 'Mythic landscape', confidence: 'traditional' },
  { name: 'Ismaros / Cicones', lat: 40.96, lng: 25.37, type: 'Odyssey', period: 'Homeric regional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/507409' },
  { name: 'Djerba / Lotophagitis', lat: 33.7833, lng: 10.8833, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/344440' },
  { name: 'Cyclopes’ Coast', lat: 37.5633, lng: 15.1619, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional' },
  { name: 'Lipari / Aeolia', lat: 38.467, lng: 14.957, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/462284' },
  { name: 'Formiae / Telepylus', lat: 41.2557, lng: 13.6012, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/432839' },
  { name: 'Aeaea / Circeo', lat: 41.232, lng: 13.055, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional' },
  { name: 'Ephyra / Acheron', lat: 39.236, lng: 20.534, type: 'Odyssey', period: 'Underworld analogue', confidence: 'mythic', pleiadesUrl: 'https://pleiades.stoa.org/places/531011' },
  { name: 'Messina Strait', lat: 38.254, lng: 15.64, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional' },
  { name: 'Sicilia / Thrinacia', lat: 37.5896, lng: 14.0576, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/462492' },
  { name: 'Gozo / Ogygia', lat: 36.0444, lng: 14.2512, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/462213' },
  { name: 'Corcyra / Scheria', lat: 39.62, lng: 19.8665, type: 'Odyssey', period: 'Traditional placement', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/530835' },
  { name: 'Tempe / Daphne', lat: 39.876, lng: 22.5665, type: 'Gods', period: 'Literary landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/541131' },
  { name: 'Thespiae / Echo', lat: 38.2935, lng: 23.1549, type: 'Metamorphosis', period: 'Literary landscape', confidence: 'traditional', pleiadesUrl: 'https://pleiades.stoa.org/places/541141' },
  { name: 'Gorgons’ Shore / Pegasus', lat: 35.9, lng: -7.2, type: 'Heroes', period: 'Mythic direction', confidence: 'mythic' },
  { name: 'Yanartaş / Chimera', lat: 36.4316, lng: 30.4561, type: 'Heroes', period: 'Traditional placement', confidence: 'traditional' },
]

export const ancientRegions: Array<Point & { name: string; kind: 'land' | 'sea' }> = [
  { name: 'MAGNA GRAECIA', lat: 38.9, lng: 16.2, kind: 'land' },
  { name: 'HELLAS', lat: 39.2, lng: 22.4, kind: 'land' },
  { name: 'MACEDONIA', lat: 41.05, lng: 22.7, kind: 'land' },
  { name: 'THRACE', lat: 41.75, lng: 27.0, kind: 'land' },
  { name: 'ASIA MINOR', lat: 38.8, lng: 31.0, kind: 'land' },
  { name: 'CRETE', lat: 35.15, lng: 24.6, kind: 'land' },
  { name: 'LYCIA', lat: 36.8, lng: 29.7, kind: 'land' },
  { name: 'AEGEAN SEA', lat: 38.3, lng: 25.2, kind: 'sea' },
  { name: 'IONIAN SEA', lat: 37.4, lng: 18.7, kind: 'sea' },
  { name: 'SICILIA', lat: 37.6, lng: 13.7, kind: 'land' },
]

export const odysseyRoute: Point[] = [
  { lat: 39.9575, lng: 26.2389 },
  { lat: 40.96, lng: 25.37 },
  { lat: 33.7833, lng: 10.8833 },
  { lat: 37.5633, lng: 15.1619 },
  { lat: 38.467, lng: 14.957 },
  { lat: 41.2557, lng: 13.6012 },
  { lat: 41.232, lng: 13.055 },
  { lat: 39.236, lng: 20.534 },
  { lat: 40.5808, lng: 14.4296 },
  { lat: 38.254, lng: 15.64 },
  { lat: 37.5896, lng: 14.0576 },
  { lat: 36.0444, lng: 14.2512 },
  { lat: 39.62, lng: 19.8665 },
  { lat: 38.4003, lng: 20.6928 },
]

export const collections = [
  {
    title: 'Olympians',
    count: 12,
    note: 'Power, jealousy, and sacred order',
    color: '#bf8e42',
    art: './assets/scene-prometheus.webp',
  },
  {
    title: 'Heroes',
    count: 18,
    note: 'Mortals who pay the price of victory',
    color: '#94422d',
    art: './assets/scene-medusa.webp',
  },
  {
    title: 'Monsters',
    count: 14,
    note: 'Creatures waiting at the edge of order',
    color: '#53624c',
    art: './assets/scene-labyrinth.webp',
  },
  {
    title: 'Trojan Cycle',
    count: 10,
    note: 'One war, hundreds of destinies',
    color: '#71503c',
    art: './assets/scene-trojan-horse.webp',
  },
]
